### ISSUE TITLE
4 Artikel im Warenkorb -> erster Artikel zeigt Kurzbeschreibung

### ISSUE THREAD

**Issue by amenk** [firegento/firegento-magesetup#100]
Reproduzierbar wie folgt:
1. Artikel in Warenkorb legen -> alles i.O.
2. Artikel in Warenkorb legen -> alles i.O.
3. Artikel in Warenkorb legen -> alles i.O.
4 Artikel in Warenkorb legen -> beim ersten wird die Kurzbeschreibung angezeigt

Das ganze scheint hier zu passieren: https://github.com/firegento/firegento-magesetup/blob/master/src/app/code/community/FireGento/MageSetup/Helper/Catalog/Product/Configuration.php#L52

Wozu ist diese Funktionalität gut?

**Comment by kkoepke** [comment]
Ich kann das Problem bestätigen. Bei mir sollen die Attribute aber für alle Produkte angezeigt werden.

Für die Attribute 'short_description' und 'delivery_time' ist "sichtbar im Bestellprozess" auf Ja gestellt, die Attribute werden aber erst ab dem 4 Produkten im Warenkorb beim 1. Produkt ausgegeben, ab 5 Produkten beim 2. usw. 

Bei den 3 zuletzt in den Warenkorb gelegten Produkten werden die Attribute also nie ausgegeben.

Getestet in Magento 1.9.0.1 und MageSetup 2.1.0

Hat wer eine Idee?

@amenk Wenn ich dich richtig verstehe, willst du die Attribute gar nicht ausgeben? Wenn du in der Attributverwaltung für die betreffenden Attribute "sichtbar im Bestellprozess" auf Nein stellst, sollten sie verschwinden.

**Comment by nhp** [comment]
iirc passiert das durch den mini_cart im rwd theme. jedenfalls habe ich es ohne den mini_cart nicht ansonsten ist es reproduzierbar.

**Comment by kkoepke** [comment]
Ok, auch unabhängig vom rwd theme konnte ich es in dem betreffendem Shop nachvollziehen.

Sofern im Header der mini cart (app/design/frontend/base/default/template/checkout/cart/sidebar/default.phtml) im Header eingebunden ist werden für die dort angezeigten Artikel (zuletzt hinzu gefügt) die Attribute im Warenkorb nicht mehr ausgegeben.

**Comment by avstudnitz** [comment]
Wir konnten den Fehler zwar nicht reproduzieren, haben aber einen verwandten Bug gefunden und behoben. @kkoepke @nhp könntet ihr testen, ob der Fehler noch auftaucht?

**Comment by therouv** [comment]
Erfolgreich getestet.

**Comment by nhp** [comment]
Ja sieht so aus als ob es damit behoben ist.
