### ISSUE TITLE
"Versandkosten" aus Kategorieansicht entfernen

### ISSUE THREAD

**Issue by agentlucky** [firegento/firegento-magesetup#112]
Aus designtechnischen Gründen muss ich in der Kategorieansicht auf die Angaben "Inkl. 19% MwSt., zzgl. Versandkosten" verzichten. Allerdings nur bei "hover". Also in der "regular" Ansicht soll es angezeigt werden und in der "hover" Ansicht ausgeblendet werden. Die MwSt. Angaben konnte ich via css ausblenden. Die "Versandkosten" werden in der "hover" Ansicht einfach nur als Link ausgegeben, anders als bei "regular", wo sie noch die Klasse "shipping-cost-details" zugewiesen bekommen.
Heißt, ich kann es nicht direkt via css ansprechen, um es auszublenden.
Ich vermute, dass jetzt php is Spiel kommt, wo ich mich leider nicht genug auskenne.
Ich hoffe, ich konnte mein Problem verständlich genug beschreiben und hoffe auf eine Lösung.
Danke schonmal im Voraus...

**Comment by therouv** [comment]
Diese Funktionalität kann nicht in MageSetup umgesetzt werden, da sie zu Shop-spezfisch ist und hier mehr Informationen nötig wären.
