### ISSUE TITLE
Adjust tax settings to new EU tax laws from 2015

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-magesetup#120]
AFAIK: If sending to a foreign EU country, the tax of that country should be used instead of the own country's tax.
We should adjust the tax settings. Probably it's a good idea to use the Magento 1.9 feature of a fixed gross price, if available.

**Comment by avstudnitz** [comment]
It's possible with Magento and MageSetup, but it's a lot of work, as many new tax classes, tax rules and tax rates have to be added automatically. It's currently out of scope of MageSetup.
If anyone wants to sponsor that feature, please contact us.

**Comment by sprankhub** [comment]
Do you have any estimation how much such a feature would cost? We may start a Kickstarter project for it :-) No, just kidding, but an estimation would be helpful in any case.

BTW I think this is also a very good possibility to build a paid extension. This paid extension may be completely independent or may be built on top of MageSetup.

**Comment by avstudnitz** [comment]
It would be at least 4 hours of work for someone who knows the tax setup system of MageSetup. Including testing and finding out all tax rates for all EU countries, I'd probably calculate at least 8 hours for that. You'd have to rewrite the Tax Setup model and probably the tax.xml files (or provide a seperate XML file just for the tax rates of the individual countries).

**Comment by sprankhub** [comment]
Alright, sounds fair. I would sponsor 2 hours. Maybe there are some others who would sponsor the rest.

**Comment by sprankhub** [comment]
This may be interesting for people searching for a solution:
- https://www.taxamo.com/magento-eu-vat-module/
- http://www.magentocommerce.com/magento-connect/taxamo-for-new-eu-vat-calculation-and-moss-reporting-1.html
