### ISSUE TITLE
Adjust to new Magento 1.9.1 email templates

### ISSUE THREAD

**Issue by avstudnitz** [firegento/firegento-magesetup#121]
Probably, positions of imprint details, conditions etc. have to be adjusted for the new email templates. Haven't tested that yet.

**Comment by avstudnitz** [comment]
Nothing to do as the structure of the email template remains the same.

**Comment by hpvd** [comment]
hmm. Maybe there is the need for inserting place holders like I tried to describe in the ticket you attached to this one?
"adopt to new email setup process of Magento 1.9.1 #125"

**Comment by avstudnitz** [comment]
@hpvd The problem with that is that we don't want all includes in all emails. We must decide per email type which includes should be appended. Thus, it wouldn't work if we included it into the footer.html.
If you are of different opinion, I'd be glad if you'd provide a pull request (for the development branch please).
