### ISSUE TITLE
Keine Checkboxen im Checkout

### ISSUE THREAD

**Issue by danielkoch** [firegento/firegento-magesetup#123]
Mit dem BGH-Urteil vom 15.5.2014, III ZR 368/13 wurde klar gestellt, dass das Abhaken der aktuell im Checkout hinzugefügten Bedingungen (Widerrufsbelehrung, ....) nicht ausreichend ist. Somit sind die Checkboxen im Checkout nicht notwenig. Stattdessen reicht m.E. die Übermittlung der nötigen Informationen in den jeweiligen Bestätigungen (dies ist bereits vorgesehen).
Ist es aktuell möglich, die "Terms and Conditions" und "Revocation " anzuzeigen, jedoch ohne Checkboxen?

**Comment by mklooss** [comment]
Es gibt in den Bestellbedingungen eine Option, mit dem man die Checkbox an und aus machen kann.

**Comment by danielkoch** [comment]
Unter System > Configuration > Checkout: Enable Terms and Conditions?
Dies deaktiviert jedoch komplett Text/Link und Checkbox. Man müsste nur die "Checkbox-Funktionalität" ausschalten können, Text/Link sollte weiterhin angezeigt werden.

**Comment by mklooss** [comment]
Durch magesetup kommt unten auch eine neue option welches nur die checkbox deaktivieren kann.

Hab gerade kein magento zur Hand.

**Comment by danielkoch** [comment]
"Display Additional Information"? Dies ist m.E. eher eine Zusatzoption bzw. ein Zusatztext – der erscheint auch an einer anderen Stelle.

**Comment by avstudnitz** [comment]
Nein. Unter "Verkäufe" -> "Bestellbedingungen". Bei jeder Bedingung gibt es ein Dropdown-Feld "Erforderlich" (ja/nein), das regelt, ob eine Checkbox angezeigt wird oder nicht.

**Comment by danielkoch** [comment]
Genau das ist das was ich gesucht habe. Danke.

**Comment by MMonia** [comment]
Ich habe folgendes Problem. Vielleicht kann mir jemand helfen. 
Nach der Installation von FireGento MageSetup bekomme ich fehlermeldung im Warenkorb: Üngültiger Attributtyp. Deaktiviere ich jedoch im Backend Bestellbedingungen geht der Vorgang ohne Probleme weiter. Woran kann das liegen?? Nutze Magento Version 1.9.1.0.
