### ISSUE TITLE
adopt to new email setup process of Magento 1.9.1

### ISSUE THREAD

**Issue by hpvd** [firegento/firegento-magesetup#125]
In Magento 1.9.1 the email setup/building process was changed
and the email templates are responsive.
.....
Customizing the Header or Footer in Transactional Emails

In earlier Magento CE and EE versions, each transactional email template contained a copy of the HTML for the header and footer. To make it easier to customize transactional emails, the header and footer HTML is now centralized in the following template...

The header and footer template files get included in the transactional emails using a new template directive
....

see
www.magentocommerce.com/knowledge-base/entry/ee1141-ce191-responsive-email

=> would be great if magesetup adopted these changes too

**Comment by avstudnitz** [comment]
See #121
