### ISSUE TITLE
Price not changing on front-end.

### ISSUE THREAD

**Issue by egg74** [firegento/firegento-magesetup#128]
Hi,

I've a strange issue, I hope you can help.

When I make a price change in the admin panel, the change in price is not seen on the front-end page.

However, if I make the change via MAGMI, the price is then updated.

My products are setup as group products, using block:  
Mage_Catalog_Block_Product_View_Type_Grouped (via the dev hints).

The actual price is being shown via: "FireGento_MageSetup_Block_Catalog_Product_Price" according to the hints. So, that's why I'm thinking this problem could like with the magesetup extension.

Any advice?
Thanks

**Comment by therouv** [comment]
@egg74 I don't think, that MageSetup is the issue here as I tried to verify the problem and could not reproduce it. I guess the reason is cache or price index.

**Comment by egg74** [comment]
yes, you are right - I'm an idiot. The problem was related to MAGMI. The import file/config was somehow incorrect. Having cleaned the import files and adjusted everything - the prices work again. Sorry and thanks!
