### ISSUE TITLE
After intalling Not sending Order confirmation e-mail (sendet keine Bestellbestätigungs-E-Mail)

### ISSUE THREAD

**Issue by taracho** [firegento/firegento-magesetup#129]
After installing Magesetup Order confirmation e-mail is  not sending. But Other Email like invoice...... is beeing sent.

What is the problem?

**Comment by avstudnitz** [comment]
The problem isn't MageSetup. It's probably Magento 1.9.1.0 which is sending order confirmation emails via Cronjob (see http://www.aschroder.com/2015/01/sending-emails-by-queue-in-magento-1-9-1/).

**Comment by taracho** [comment]
But i without this extention. The Email funktion was ok. And now i reistall it again on a simple magentoshop. To see if it is realy because of the extention. At first the Order confirmation e-mail worked right an after the installation the Order confirmation e-mail did not work.

**Comment by avstudnitz** [comment]
Which Magento version?

**Comment by avstudnitz** [comment]
MageSetup isn't yet compatible to the new responsive email templates from Magento 1.9.1.0. We will fix it this weekend probably.

**Comment by taracho** [comment]
1.9.1

oh.Thanks

**Comment by taracho** [comment]
Top! Good Work if you fix it till this weekend

**Comment by therouv** [comment]
@taracho We tested it today but we can't reproduce the issue. MageSetup is already compatible with the new responsive email templates. 

For further investigation, please check if the email was inserted in the table `core_email_queue` and if the cronjob was set up properly.
