### ISSUE TITLE
How to update to latest release?

### ISSUE THREAD

**Issue by Arn2014** [firegento/firegento-magesetup#131]
Hi Firegento team,

I've searched and read all info about using firegento magesetup, but can't find information
on how to update to the newest version on a live multi-store setup.

 I know this isn't a support forum , but there is no other place i can drop this question..

- Is it only a matter of uploading the latest release files true ftp ? overwriting the existing files?..
or do i run into troubles when i do that..?

Thanks for your support!

Best

A

**Comment by therouv** [comment]
Hi @Arn2014, there are multiple ways:
* Composer
* MagentoConnect
* SSH/FTP

**Comment by Arn2014** [comment]
Hi therouv,

thanks for your quick response..
I prefer the FTP way...is uploading and overwriting the "simple" and correct procedure..
nu further actions needed?, appart form flushing cache..?

Thanks!

Best,

A

**Comment by riconeitzel** [comment]
As "uploading" is just "edit" or "replace" but not "delete" you should also make sure that there are no outdated files left in the modules directories.
