### ISSUE TITLE
Price-Info

### ISSUE THREAD

**Issue by StevenSch** [firegento/firegento-magesetup#132]
The Price-Info does not work for bundle-products with Version 2.2.1.
I m back on price_info.phtml from 2.1.0 it works.

**Comment by mmodler** [comment]
+1

price-info.phtml won't show anything on article detail page of a bundle product (fixed price, tax class set).

Reverting to 2.1.1 / 2.1.0 will show "Zzgl." instead of "Inkl." on simple product detail pages

**Comment by kkoepke** [comment]
+1

**Comment by elayoutable** [comment]
+1

price_info.phtml (2.2.1) - simple, grouped - ok ("incl."), bundle - nothing
price_info.phtml (2.1.0) - simple, grouped - ("excl."), bundle - ok ("incl.")

**Comment by mmodler** [comment]
Anything new on this issue? Ideas for a workaround?

**Comment by mmodler** [comment]
I have created a pull request for this isse, see #170

**Comment by elayoutable** [comment]
price_info.phtml (2.2.1) - Grouped ok in the category view, but in the product view as an upselling product (e.g.) -> incl. 0 % tax instead of 19%

**Comment by mmodler** [comment]
Is there a reason why my pr can't be merged?

**Comment by riconeitzel** [comment]
Yes … No one has time to review it :-( But it's still here and we're still aware of it. But firegento is still just a voluntary side project for everyone.

**Comment by mmodler** [comment]
Yes, i understand. I asked because my change is a one liner which should not have any side effekts outside the bundle display. and without it bundle prices on detail are displayed without "Inkl. USt., zzgl. Versandkosten" which causes a legal issue for german shops...

**Comment by Schrank** [comment]
Did anyone test the PR beside @mmodler if yes I would love to merge it :-)

**Comment by Schrank** [comment]
Closed by #170
