### ISSUE TITLE
How to Remove the Terms and Conditions

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-magesetup#133]
From a [FireGento_Pdf issue](https://github.com/firegento/firegento-pdf/issues/211):

I do apologise if this is not the correct place.

I recently installed MadgeSetup from FireGento so that I could take advantage of the TAX / VAT display functionality.

I noticed after installation that I acquired new check boxes on the one page checkout screen

I agree [Show]
I have read the Business Terms and agree with them. [Show]
I have read the Right of Revocation. [Show]

These seem to have been installed by running the MadgeStup and not un-ticking the relevant boxes before hitting the confog button in the System panel.

I have since tried to reinstall without the check boxes being ticked, removing the extension through Magento Connect, all to no avail.

What I cannot find is any process defining how to completely remove MadgeSetup plus all of its files that it produces as part of the initial setup.

At this point I would settle for removing the additional check boxes on the checkout page but cannot locate the relevant file to do so.

Any help would be greatly appreciated.

Thanks in advance from a novice Magento person.

**Comment by sprankhub** [comment]
This can be done in the administration under Sales - Terms and Conditions. Just remove the conditions you do not want to be displayed.

**Comment by divestyle** [comment]
Hi sprankhub

If I do this then I loose all of the following

I agree [Show]
I have read the Business Terms and agree with them. [Show]
I have read the Right of Revocation. [Show]

I only want to remove

I have read the Business Terms and agree with them. [Show]
I have read the Right of Revocation. [Show]

Before I installed the extension I only had 

I agree [Show], I don't need the other two as Revocation etc does not apply for UK only sales.

**Comment by avstudnitz** [comment]
So why not only remove the conditions you want to remove?

**Comment by divestyle** [comment]
I do not know how to remove on two of the three.

**Comment by riconeitzel** [comment]
In Magento -> AdminPanel -> Catalog -> Terms and Conditions you can find all T&C's … there you can remove the two T&C's you don't need anymore.

**Comment by divestyle** [comment]
![screen shot2015-02-02 18_57_12](https://cloud.githubusercontent.com/assets/10800347/6006979/c3c55d56-ab0e-11e4-97c1-6b9375f69f21.png)

**Comment by divestyle** [comment]
I am using the CE addition and 1.9 and under  catalog I do not have that option to select

**Comment by riconeitzel** [comment]
I know why: I'm dumb :D So sorry … try "Orders" … not "Catalog" … :-/

**Comment by divestyle** [comment]
![screen shot 2015-02-02 at 19 13 28](https://cloud.githubusercontent.com/assets/10800347/6007091/a726440c-ab0f-11e4-8b47-ed7ed3a7c391.png)

All I have are these to select from

**Comment by riconeitzel** [comment]
Jesus … it's too late for me … Sales :D

**Comment by divestyle** [comment]
I feel pretty dumb right now! I should be able to sort this but it is stumping me big time

**Comment by riconeitzel** [comment]
When anyone at anytime discovers THAT thread I'll loose all my credibility :dancer:

**Comment by divestyle** [comment]
You sir are a genius! Why did I not spot that :0| Thank you for getting me sorted. Brilliant, one very happy bunny.

**Comment by riconeitzel** [comment]
you're welcome :)

**Comment by divestyle** [comment]
Just delete the thread, no complaints from me and would save me a red face also :+1:

**Comment by riconeitzel** [comment]
I'll keep it for other users stumbling at the same issue :-) it's blaming me too, so: welcome at the club! :hand: (highfive!)
