### ISSUE TITLE
Update to 2.2.1 breaks checkout with banktransfer payment

### ISSUE THREAD

**Issue by tecjam** [firegento/firegento-magesetup#135]
I had version 2.1 installed and used the ConnectManager to update to 2.2.1 - after this the checkout would not work with payment type banktransfer:

/checkout/onepage/savePayment/

POST: payment[method]   banktransfer - 200 OK

Response:

Ungültiger Attributtyp: %s{"goto_section":"review","error":"Ung\u00fcltiger Attributtyp: %s"}

Clicking continue will not load - all it does is throw a .js error: Invalid Attribute ...

**Comment by hpvd** [comment]
which Magento version are you using?

**Comment by tecjam** [comment]
Hi hpvd, yes that was me and the magento version is 1.9.1

**Comment by tecjam** [comment]
Hi again, I tried the updated Version 2.2.2 on a local store - the exact same thing happens.

**Comment by MMonia** [comment]
I have the same Problem

**Comment by MMonia** [comment]
![fehler_kasse](https://cloud.githubusercontent.com/assets/11474073/7449530/a6e7cc70-f238-11e4-9774-111c9f931d86.jpg)
Jemand ne Idee woran das liegen könnte ?

**Comment by motau** [comment]
Ich hab das Problem mit dem "Ungültigen Attributtyp" gefunden und behoben:
 - das Modul-SQL-update "mysql4-upgrade-2.1.1-2.2.0.php" wurde offenbar beim installieren 
übersprungen, warum auch immer.
- somit fehlte das Produktattribut "revocation_product_type"

Einfache Lösung: 
1. In der config.xml die Version hochzählen, bei mir von 2.2.2 auf 2.2.3: 
2. Die Installer Datei mysql4-upgrade-2.1.1-2.2.0.php nach mysql4-upgrade-2.2.2-2.2.3.php
kopieren
3. im Backend Caches löschen/abmelden/wieder anmelden
4. Attribut prüfen: "revocation_product_type" 
    - zu finden unter Backend/Katalog/Attribute/Attribute verwalten - Code filtern

**Comment by MMonia** [comment]
Vielen Dank, hat alles super geklappt.

**Comment by riconeitzel** [comment]
Habe für die Ursache ein neues Ticket geöffnet #199
