### ISSUE TITLE
[Germany] Account Confirmation is also SPAM

### ISSUE THREAD

**Issue by mklooss** [firegento/firegento-magesetup#138]
German news about E-Mail Register Confirmation:

http://www.shopbetreiber-blog.de/2015/02/04/shop-bestaetigt-eroeffnung-eines-kundenkontos-und-wird-abgemahnt/

http://www.golem.de/news/kundenkonto-urteil-verbietet-mail-zu-anmeldebestaetigung-fuer-onlineshop-1502-112238.html

**Comment by riconeitzel** [comment]
it’s only spam if you don’t use double opt-in for account registration … built-in in magento, just needs to be enabled there …

**Comment by winkelsdorf** [comment]
@mklooss & @riconeitzel Thanks for the Info!
