### ISSUE TITLE
Mailvorlagen für Magento 1.9.1 

### ISSUE THREAD

**Issue by tobi-pb** [firegento/firegento-magesetup#142]
In Magento 1.9.1 sind die Mailvorlagen nun Responsive. Das sollten wir in den German-Setup Templates noch nachziehen.  

Wenn noch niemand daran arbeitet übernehmen wir auch gerne die arbeiten. Bitte nur kurz freigeben :)

**Comment by hpvd** [comment]
sounds great. They are not only responsive but also handle header and footer in a different way
see https://github.com/firegento/firegento-magesetup/issues/125

**Comment by avstudnitz** [comment]
Freigegeben von mir aus. Aber: wir haben doch gar keine Mailvorlagen drin - wir ergänzen die bestehenden nur dynamisch um AGB, Datenschutz etc. Und das funktioniert mit den neuen Templates genau wie mit den alten. Oder verpasse ich etwas?

**Comment by riconeitzel** [comment]
Andreas hat Recht – ihr nutzt den Standard, der, wenn das de_DE vorher installiert ist, schon die neuen Templates nutzt.

Liebe Grüße
 Rico

**Comment by tobi-pb** [comment]
Ah guck mal an. Das du die neuen schon drin hattest wusste ich nicht Rico. Dann ist ja alles prima und wir müssen nur dran denken das Language Pack zu aktualsieren :-)

**Comment by winkelsdorf** [comment]
Mal eine Verlinkung von hier, da ich mit einem mageSetup Mail Template ein Layoutproblem habe (out of the box): https://github.com/firegento/firegento-magesetup/issues/162
