### ISSUE TITLE
magento2 development

### ISSUE THREAD

**Issue by davidverholen** [firegento/firegento-magesetup#143]
Hey,

is there a Plan for this module regarding magento2 migration?

Just asking since this will be an important module for all German(and other) Magento 2 Shops.

**Comment by riconeitzel** [comment]
@therouv is working on it.

**Comment by paul-siteway** [comment]
@therouv
Any news, or possible release date?  :-)

**Comment by sprankhub** [comment]
You can have a look at the repo: https://github.com/firegento/firegento-magesetup2

But some up-to-date insider information from @therouv would be cool.

**Comment by Schrank** [comment]
@michael-hxx have you read the comment by Simon?

https://github.com/firegento/firegento-magesetup/issues/143#issuecomment-171929455

**Comment by michael-hxx** [comment]
I am using the old germansetup module. before migration i will update that extension and after that i will follow the steps in the link #143 (comment).
i got an error after migration completed successfully. e.g. i see the template data in order adress view..
