### ISSUE TITLE
Empty page, when I open MageSetup in BE

### ISSUE THREAD

**Issue by Maksold** [firegento/firegento-magesetup#145]
When I open MageSetup, I see empty page => http://note.io/1GNxUfo
I checked log, but there is no errors. I have this problem on CE 1.9.0.1 and 1.9.1.0. Any ideas?

**Comment by therouv** [comment]
Hi @Maksold - it seems that you have installed the extension via composer or modman. In this case your have to enable symlinks in the system configuration. The path is: *System > Configuration > Advanced > Developer > Template Settings > Allow Symlinks*.

**Comment by Maksold** [comment]
@therouv Yes, I installed it via magesetup. I enabled Allow Symlinks and now I also have empty page => http://note.io/1GghBuk Cleared cache and tied to logout/login, but it doesn't help.

**Comment by Maksold** [comment]
I fixed this issues by reinstalling module.
