### ISSUE TITLE
checkout.css anpassen

### ISSUE THREAD

**Issue by joh-klein** [firegento/firegento-magesetup#146]
Was ist die best practice, wenn man die Werte in der checkout.css ändern will? (Oder komplett weglassen möchte?)

**Comment by therouv** [comment]
@joh-klein CSS-Datei in das eigene Theme kopieren und anpassen.

**Comment by joh-klein** [comment]
Ich habe es jetzt erstmal mit `removeItem` das css wieder rausgeschmissen. So wie ich dich aber verstehe, reicht es, dass ich die entsprechende CSS-Datei im passenden Verzeichnis einbinde?

**Comment by winkelsdorf** [comment]
Ich bin zwar nicht therouv, aber die Antwortet ist: ja.

**Comment by riconeitzel** [comment]
ich bin zwar nicht ihr alle, aber ich würde eher ne eigene CSS Datei einbinden und die Regeln anpassen, die mich stören … override durch fallback finde ich immer nicht so schön.

**Comment by winkelsdorf** [comment]
@riconeitzel :+1:
