### ISSUE TITLE
PayPal Express Kaufen Button falsch aktiv

### ISSUE THREAD

**Issue by Kipperlenny** [firegento/firegento-magesetup#151]
Wenn man mit PayPal Express gekauft hat, ist auf der Review Seite der "Jetzt kaufen" Button blau und klickbar:

![kaufen](https://cloud.githubusercontent.com/assets/563328/6871616/337caa00-d4a4-11e4-80f4-b1ecb2dedc42.png)

Erst wenn ich eine Checkbox aktiviere, wird der Button Grau und ist nicht mehr klickbar (korrekter Weise). Sobald alle Checkboxen aktiv sind, kann man den Button (korrekter Weise) wieder klicken.

Dadurch klicken die Kunden bisher auf "Jetzt kaufen" und eine "Zahlung fehlgeschlagen" Mail wird versandt.

Also Lösung:

Der "Jetzt Kaufen" Button sollte NICHT KLICKBAR und GRAU sein nach dem PayPal Kauf.

**Comment by gfobe** [comment]
Auf der Paypal-Express-Review-Seite werden die Standard-Magento Agreements genommen statt der von MageSetup. Pull-Request in #150 behebt das Problem.

**Comment by Kipperlenny** [comment]
perfekt - ins XML eingetragen, Cache geleert und funzt :) danke!

**Comment by l-carb-shop** [comment]
I am using Magento 1.9.2.1 and have same problem. The suggested Solution does not help in my case
