### ISSUE TITLE
VAT setup not ready for EU download only articles.

### ISSUE THREAD

**Issue by rarog** [firegento/firegento-magesetup#152]
I'm not sure how to fix this properly programatically as currently it seems that just a matrix is built form VAT rates.
Since 2015-01-01 download only articles have to have applied the tax rate of the customer billing country, so same article has 19% VAT for Germany, 20% for Austria and 25% for Sweden.

http://www.ecwid.com/blog/how-the-new-value-added-tax-guidelines-for-selling-digital-goods-affect-your-online-store.html

**Comment by avstudnitz** [comment]
This was already discussed in #120. See there.
