### ISSUE TITLE
error after switching to magesetup: Module "IntegerNet_GermanStoreConfig" requires module "FireGento_GermanSetup"

### ISSUE THREAD

**Issue by jangott** [firegento/firegento-magesetup#154]
We are getting the following error

Well, but when FireGento_GermanSetup were disabled, we’ve got an error: 
Module "IntegerNet_GermanStoreConfig" requires module "FireGento_GermanSetup".

Any ideas? We are on 1.7.0.2

**Comment by avstudnitz** [comment]
Edit the file app/etc/modules/IntegerNet_GermanStoreConfig.xml and replace GermanSetup with MageSetup.

**Comment by jangott** [comment]
Danke!!
Andreas von Studnitz <notifications@github.com> schrieb am Mi., 8. Apr.
2015 um 18:32:

**Comment by jangott** [comment]
Thanks, here's feedback from our dev:

It will not work. If I replace this, it will remove error, but other errors
will appear, because in module IntegerNet_GermanStoreConfig it uses GermanSetup
module. For example, in file
app/code/community/IntegerNet/GermanStoreConfig/Block/Form.php on line 28
there is a call Mage::helper('germansetup')->__('Shop Name');
It will throw an error, because module 'germansetup' is disabled, and
helper for module MageSetup should be called Mage::helper('magesetup'), so,
it will not work.

What now :(

Andreas von Studnitz <notifications@github.com> schrieb am Mi., 8. Apr.
2015 um 18:32 Uhr:

**Comment by riconeitzel** [comment]
That Bug is related to https://github.com/integer-net/GermanStoreConfig/issues
