### ISSUE TITLE
Skip Installation causes 404 

### ISSUE THREAD

**Issue by arvenom** [firegento/firegento-magesetup#159]
After installing the extension if I click on Skip Installation it returns a 404. 
Not sure if its the url /index.php/admin/admin/magesetup/skip/key

**Comment by rum-neutralo** [comment]
Same for me; Any Solution? Magento: 1.9.1.1

**Comment by Schrank** [comment]
The action exists. No clue why this doesn't work.
https://github.com/firegento/firegento-magesetup/blob/master/src/app/code/community/FireGento/MageSetup/controllers/Adminhtml/MagesetupController.php#L81-L87

**Comment by Schrank** [comment]
I can't reproduce the problem in the current develop branch.
