### ISSUE TITLE
at checkout - always all 3 revocation texts are shown

### ISSUE THREAD

**Issue by Incendii** [firegento/firegento-magesetup#160]
I only have physical goods in my shop. So I don't need the revocation texts for digital goods or services.

no matter which type i choose for my products (Warenlieferung) - when you buy a product in the shop it always shows all 3 revocation texts: 

How can I change it, that there is only the standard first one for physical goods?

"- Ich habe die Widerrufsbelehrung gelesen. [Anzeigen]
- Ich stimme ausdrücklich zu, dass Sie vor Ablauf der Widerrufsfrist mit der Ausführung des Vertrages beginnen. Mir ist bekannt, dass ich durch diese Zustimmung mit Beginn der Ausführung des Vertrages mein Widerrufsrecht verliere.
- Ich bin einverstanden und verlange ausdrücklich, dass Sie vor Ende der Widerrufsfrist mit der Ausführung der beauftragten Dienstleistung beginnen. Mir ist bekannt, dass ich bei vollständiger Vertragserfüllung durch Sie mein Widerrufrecht verliere."

**Comment by Incendii** [comment]
nochmal kurz auf deutsch.

Ich habe bei allen Artikeln "Warenlieferung" als Produkttyp für Widerrufsrecht eingestellt.
Beim Checkout werden allerdings trotzdem immer alle 3 Widerrufsrechttexte angezeigt und stehen auf Zwang bevor jemand kaufen kann.

Kann mir jemand helfen wo das Problem liegen könnte?
Leider habe ich die Extension schon live - und auch ein Versuch der Deinstallation der Extension hat das Problem nicht behoben.

**Comment by Incendii** [comment]
noch eine Anmerkung:
Unter der Artikelansicht bei Produkttyp für Widerrufsrecht steht bei default immer Standardwert (Konfiguration). Ich habe diesen Wert überall auf Warenlieferung geändert. Trotzdem das gleiche Problem.  Wo gibt es eigentlich den Reiter im Konfigurationsmenü, wo man den Standardwert einstellt? Kann den nirgendwo finden.

**Comment by Incendii** [comment]
kann es sein, das es ein Problem in Zusammenhang mit dieser Extension und der BasePrice Extension gibt? http://www.magentocommerce.com/magento-connect/baseprice-modul-basic-grundpreis-modul-pangv.html

Leider lässt sich die Base Price extension nicht deinstallieren um zu testen - da nach der deinstallation die Artikeldatenbank nicht mehr korrekt funktioniert.

**Comment by avstudnitz** [comment]
Zum Deinstallieren des Baseprice-Moduls gibt es unter http://www.nr-apps.com/faq/content/21/92/en/how-can-base-price-pro-be-uninstalled-completely.html eine Anleitung.

**Comment by Incendii** [comment]
Danke für die Deinstallationsanleitung für Baseprice - leider bin ich nur Laie und habe keine Ahnung wie ich überhaupt auf meine Datenbank direkt access bekomme. Ich verwende eigentlich nur das Magento Backend und FTP Zugang. ... Kann es denn überhaupt an der Baseprice Extension liegen?

Gibt es irgendwo ein Konfigurationsmenü, wo ich etwas zu den Widerrufsrechten einstellen kann?
Bisher habe ich nur die eine Option im Artikel selbst (unter Price) gefunden.

**Comment by Incendii** [comment]
Oder kann ich irgendwie die Widerrufsbedingungen für Digital und service manuell irgendwo rauslöschen? Ich brauche eh nur Warenlieferung.

**Comment by Incendii** [comment]
kann mir irgend jemand helfen?

**Comment by winkelsdorf** [comment]
**DE**
Gleiches Problem bei frischer 1.9.1.0 Installation mit mehreren StoreViews (Sprachen). Tagesaktueller Dev Source von MageSetup wird über Composer genutzt.

Genauere Beschreibung: Problem tritt nur bei PayPal Express Checkout wenn Bestellübersicht **nicht** übersprungen wird (payment/paypal_express/skip_order_review_step wird aufgerufen). Zusätzlich ist der normal Checkout auf OnePage gestellt und läuft ohne doppelte Meldungen durch.

Der Screenshot zeigt die Bestellübersicht nach Nutzen von PayPal Expresskauf und Authorisierung (PayPal Sandbox genutzt).

**EN**
Same problem here with fresh 1.9.1.0 Installation using multiple StoreViews (for languages). Using fresh MageSetup source using Composer.

Details: Only PayPal Express Checkout is affected if Order Review is **not** skipped. Beside PayPal Express common checkout is set to OnePage which runs fine without multiple T&C messages.

Screenshot shows Order Review Page after using PayPal Express Checkout and Authorization (using PayPal Sandbox).

![screen shot 2015-04-25 at 13 19 43](https://cloud.githubusercontent.com/assets/1413291/7332897/984669c4-eb58-11e4-8552-d1e147f57743.png)

**Comment by puresilk** [comment]
In your backend, go toVerkäufe -> Bestellbedingungen then choose the items which you do not want displayed and disable them. (click on each, set Status to "Deaktiviert" and click "Bedingung speichern")

**Comment by sprankhub** [comment]
I can confirm this issue. This should be fixed.

**Comment by kopfnick** [comment]
Ich habe genau das selbe Problem - gibt es einen Workaround/Quickfix?

**Comment by sprankhub** [comment]
@kopfnick most shops do not need these digital revocation texts, so disabling them under Sales - Terms and Conditions as a quick fix should be fine for most shops.

**Comment by kopfnick** [comment]
@sprankhub Thanks for your help, i looked in the wrong place, i was sure it would be in the system settings somewhere...

**Comment by Bingo2000** [comment]
Does any one find a solution to this?

**Comment by riconeitzel** [comment]
as I can see we have mixed issues here, am I wrong?! So which issues are still open and valid?! 

I don't think that fixing a broken paypal template is objective to this group. so that one would be marked as invalid then?!

**Comment by sprankhub** [comment]
I do not see any mixed issues here. I did not test again, but I could confirm that by default, all three revocation texts were shown on the PayPal Express review page even if no digital products have been bought. I do not see that this is fixed yet...? And I do not see that the issue has something to do with a broken PayPal template...?

**Comment by JanSiero** [comment]
Duplicate of 
https://github.com/firegento/firegento-magesetup/issues/151
Fixed with
https://github.com/firegento/firegento-magesetup/pull/150

**Comment by Schrank** [comment]
It seems this is fixed, if not please reopen.

**Comment by winkelsdorf** [comment]
Thanks, looks good :+1:
