### ISSUE TITLE
Unclear /paypal/express/review/ - UI leads to skipped sale

### ISSUE THREAD

**Issue by winkelsdorf** [firegento/firegento-magesetup#166]
The screenshots show the Express Review Summary, which is required in some European Countries.

As you can see, with the new default RWD the Button to finally buy is presented at the very bottom.

![screen shot 2015-05-08 at 02 33 09](https://cloud.githubusercontent.com/assets/1413291/7528594/a59ddb4e-f52a-11e4-8453-0face3684b72.png)
-- snip --
![screen shot 2015-05-08 at 02 28 04](https://cloud.githubusercontent.com/assets/1413291/7528595/a714c0c8-f52a-11e4-9033-c492c0d48867.png)

From my ecommerce experience this might likely lead to a higher rate of aborted sales, as after entering PayPal Details and seeing a Summary people might think they already bought the items (and just close the window). Especially on smaller screens.

Probably we should have a large & bold instruction before the review mentioning that the Sale is **not** completed yet?

Best somewhere between/around the heading "Bestellübersicht".

Like:
**Um den Kauf abzuschliessen, bestätigen Sie bitte nun Ihre Bestellung.**

*Wählen Sie eine Versandart aus und schliessen Sie den Kauf mit einem Klick auf den Button "Jetz Kaufen" ab. Dieser Schritt ist bei der Zahlung per PayPal Express notwendig, damit Sie vor dem Kauf Ihre Daten überprüfen können.*

My 1st thought was to place the button on the page twice (before and after the summary), but this might interfere with the German Button Solution and thus breaking the law. See https://github.com/firegento/firegento-magesetup/issues/165.

**Comment by riconeitzel** [comment]
That is a template problem of the paypal module as it works very well with the regular checkout review.

**Comment by winkelsdorf** [comment]
Ok, thanks for the feedback!
