### ISSUE TITLE
Wrong usage of nospamplease in order confirmation's revocation form attachment

### ISSUE THREAD

**Issue by winkelsdorf** [firegento/firegento-magesetup#168]
Yesterday I stumbled upon the wrong use of "nospamplease" css/js "protection" in the default order confirmations:

![screen_shot_2015-05-08_at_10_44_09](https://cloud.githubusercontent.com/assets/1413291/7533558/c8bebf92-f572-11e4-9daa-fdb83a381868.png)

Having a look at it now..

**Comment by winkelsdorf** [comment]
Tracked it down to FireGento_MageSetup_Block_Imprint_Field.

I am thinking of checking the Area via getArea() now and only use nospam for Frontend. What do you think about?

**Comment by winkelsdorf** [comment]
Aktueller Entwurf zur Diskussion:

```code
class FireGento_MageSetup_Block_Imprint_Field extends FireGento_MageSetup_Block_Imprint_Content
{
    /**
     * Render imprint field
     *
     * @return string Field value
     */
    protected function _toHtml()
    {

        if ($this->getValue() == 'email') {
            $isFrontend = ($this->getLayout()->getArea() === 'frontend');
            $isCheckout = ($this->getRequest()->getControllerModule() === 'Mage_Checkout');

            // protect email address in frontend but not in checkout scope which is used to
            // send order confirmation mails including imprint's mail address
            return $this->getEmail($isFrontend && !$isCheckout);
        }

        return $this->getData($this->getValue());
    }
}
```

Muss der getLayout->getArea() und getRequest->getControllerModule() noch anderweitig geprüft werden? Da Teil des Class Abstract, sollte es ja bei nicht festgelegtem Wert Null/Leerstring zurückgebe und damit in jedem Fall dem === widersprechen.

**Comment by winkelsdorf** [comment]
Working patch included in PR https://github.com/firegento/firegento-magesetup/pull/169

Not that beautiful by doing a string comparison but there is no other way in getting the scope information from what I can see with xdebug/phpstorm.

**Comment by winkelsdorf** [comment]
Despite there is currently no feedback: The current out of the box handling is simply wrong. **That's a bug** ;)

**Comment by riconeitzel** [comment]
I'm very sorry that no one came back here. I'm pretty sure we'll look into it sooner or later. at the moment everyone's extremely busy :-/

**Comment by winkelsdorf** [comment]
Ok, nevermind - anyway thanks for the follow up!

**Comment by riker09** [comment]
Works on my machine, too.

**Comment by winkelsdorf** [comment]
@riker09 Thanks for the feedback :+1: 

So, anybody merging? If you like..

**Comment by riconeitzel** [comment]
Merged via https://github.com/firegento/firegento-magesetup/pull/169
