### ISSUE TITLE
Checkout Problem: Popup with %S after Paymentselection

### ISSUE THREAD

**Issue by tobias-n** [firegento/firegento-magesetup#171]
![error](https://cloud.githubusercontent.com/assets/12557702/7767581/ffc000da-0073-11e5-8ae0-8ac0888513a2.jpg)

Anyone knows what the %s means? If i deactivate the Firegento_MageSetup Module then it works.

**Comment by tobias-n** [comment]
Maybe that helps anyone to help me.
![exceptions](https://cloud.githubusercontent.com/assets/12557702/8128164/090e2cb8-10fd-11e5-849d-6b1a287a6e2a.jpg)

**Comment by riconeitzel** [comment]
See #199
