### ISSUE TITLE
Inkl. 0% USt. in Search Results in Custom Template

### ISSUE THREAD

**Issue by BaldoTuttle** [firegento/firegento-magesetup#172]
I am using a modified Template from Templatemonster and the price block below price is working fine except in search results. On a search results page the price block below the price says: Inkl. 0% USt.

Does anybody has an idea, where I have to search for the error?

If I switch the theme to a standard theme, e.g. modern, the price block display correct on a search results page.

Thanx.

**Comment by Moppelfett** [comment]
I got exactly the same problem.
Any support/help here?

**Comment by riconeitzel** [comment]
Please contact the support team of your theme company. thank you.
