### ISSUE TITLE
Steuersätze falsch berechnet

### ISSUE THREAD

**Issue by markmaurerrr** [firegento/firegento-magesetup#173]
Hallo,

ich bin nun seit Tagen am verzweifeln und komme irgendwie auf keinen Nenner. 
Sowohl bei 7% als auch bei 19% kommen falsche Werte raus:

![bildschirmfoto 2015-06-05 um 10 09 30](https://cloud.githubusercontent.com/assets/7374283/8002042/d3e4c5f6-0b6b-11e5-8648-05d50f45c346.png)

7% von 6,95 sind gerundet 49 Cent. Bei solchen kleinen Beträgen kommt nicht viel bei rum, allerdings fehlen bei größeren Beträgen schnell mal zwei bis dreistellige Beträge – wegen falscher Berechnung.

Und das schlimme ist, ich kann ABSOLUT nicht nachvollziehen woher diese Rechnungsfehler kommen.

Ich habe nun echt viel ausprobiert, aber irgendwie scheint es mir als wäre ich der einzige mit diesem Problem. Weiß jemand vielleicht auf Anhieb eine Lösung?

Vielen dank schonmal im voraus!
Mark

**Comment by avstudnitz** [comment]
Die Lösung ist rein mathematisch - die rechnest die Steuer falsch aus.
Die Steuer wird auf den Nettowert berechnet, der ist hier 6,50 €. Davon 7 % sind 0,45 €.

Um vom Bruttobetrag auf den Nettobetrag zu kommen, rechnest du Brutto / 1,07 (bzw. 1,19 bei 19% Steuer).

**Comment by markmaurerrr** [comment]
Ok, sehr gut, licht im dunkeln! Bedeutet das nun, dass ich in meinen Steuerkonfigurationen irgendwas falsch eingestellt habe?

**Comment by avstudnitz** [comment]
Nein, es ist alles korrekt.
