### ISSUE TITLE
Installation exception

### ISSUE THREAD

**Issue by diver66** [firegento/firegento-magesetup#174]
Hi,

when I install magesetup, I get the following error
any idea , what I can do ?

Error in file: "/var/www/clients/client0/web2/web/app/code/community/FireGento/MageSetup/sql/magesetup_setup/mysql4-upgrade-2.1.1-2.2.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-revocation_product_type' for key 'UNQ_X2HGEAV_ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE'

Trace:
#0 /var/www/clients/client0/web2/web/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /var/www/clients/client0/web2/web/app/code/core/Mage/Core/Model/Resource/Setup.php(437): Mage_Core_Model_Resource_Setup->_modifyResourceDb('upgrade', '2.1.1', '2.2.2')
#2 /var/www/clients/client0/web2/web/app/code/core/Mage/Core/Model/Resource/Setup.php(320): Mage_Core_Model_Resource_Setup->_upgradeResourceDb('2.1.1', '2.2.2')
#3 /var/www/clients/client0/web2/web/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /var/www/clients/client0/web2/web/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /var/www/clients/client0/web2/web/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /var/www/clients/client0/web2/web/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /var/www/clients/client0/web2/web/index.php(87): Mage::run('', 'store')
#8 {main}

**Comment by diver66** [comment]
do I have to delete the entries from the ATTRIBUTE_ENTITY_TYPE_ID_ATTRIBUTE_CODE database ?

**Comment by riconeitzel** [comment]
we're still investigating the issue. See #199 for further information, thank you.
