### ISSUE TITLE
CMS pages is loaded twice

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-magesetup#175]
https://github.com/firegento/firegento-magesetup/blob/master/src/app/code/community/FireGento/MageSetup/Helper/Data.php#L52

This line loads the cms page again. We can optimize this with:

```
return Mage::getUrl(null, array('_direct' => $page->getIdentifier()))
```

Because all the checks the method is doing, are already done.

**Comment by riconeitzel** [comment]
@Schrank PR? :)

**Comment by Schrank** [comment]
check.
