### ISSUE TITLE
Tax Calculation for different Storeviews / Countries

### ISSUE THREAD

**Issue by timonalbers** [firegento/firegento-magesetup#177]
Hi guys,

our shop uses your new magesetup. Thank you. The base is configured for german market. We also choose "shipping from: Germany" to have all tax settings configured for 19% VAT. 

Now we installed a new storeview to translate the complete shop to Netherlands / 21% VAT. This shop is operated by our local company in the Netherlands. So they need to have all Prices with "Incl. 21% Tax" - instead it shows now everywhere "Incl. 19% Tax.

We have already changed the country of origin of the products to both german and netherlands.

But how we can display 19% in German Storeview or 21% in Dutch Storeview?

Thank you,
Timon

**Comment by riconeitzel** [comment]
"you're doing it wrong" … you should rather create a new website instead a new storeview and create the corresponding tax rates + rules in sales -> tax settings.
