### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Sabay1** [firegento/firegento-magesetup#178]
Hi,
I have the following problems:
1. Before I can choose in the frontend all Europe countries but right now just Germany
2. The shipping calculator is gone and for that now there is a link to the site "lieferung" (see picture below)
Or if you have any solutions I´m very thankful!
I wish a nice Sunday,
André

to 2.
![1](https://cloud.githubusercontent.com/assets/12910271/8270158/0ed4a980-17d1-11e5-9694-cffe26f81178.PNG)

**Comment by Sabay1** [comment]
Hi,
is it possible that I use the shipping calculator and not the link to the site "lieferung" (picture nr. 2)?
I hope somebody have a souloution.
Best regards,
André

**Comment by gino2014** [comment]
Hi, 
this is a magento relatet question. you can change it at "System-Konfiguration-Verkäufe-Zur Kasse-Warenkorb" and set "Geschätzte Versandkosten im Warenkorb verstecken" to nein.
regards Gino
![versandkosten](https://cloud.githubusercontent.com/assets/6517231/10045329/1fe9d530-6202-11e5-8b23-c8621e3b51ea.JPG)
