### ISSUE TITLE
Shortdescription is shown twice in cart

### ISSUE THREAD

**Issue by Bingo2000** [firegento/firegento-magesetup#180]
The short description is shown twice in cart. The support of the template says this is due using Mage Setup.
Which file do I have to edit for this issue and delete one of the short descriptions 
![bildschirmfoto 2015-06-28 um 14 33 59](https://cloud.githubusercontent.com/assets/13098762/8403944/7df8a018-1e49-11e5-913e-c9f5b35ada1d.jpg)
?

**Comment by Schrank** [comment]
MageSetup adds a new column to `catalog_eav_attribute` `is_visible_on_checkout` to show different attributes on checkout. I assume one of these is short_description.

The first one is from magento itself. We should fix this by removing short_description from this list:
https://github.com/firegento/firegento-magesetup/blob/master/src/app/code/community/FireGento/MageSetup/sql/magesetup_setup/mysql4-upgrade-1.1.4-1.2.0.php#L78-L83

**Comment by riconeitzel** [comment]
You can turn it off in the backend:

Catalog -> Attributes -> Manage Attributes 

Edit ```short_description```: scroll down to the end ```Is visible on checkout``` -> ```false``` -> save … done :-)

**Comment by Schrank** [comment]
But nonetheless is the default behavious to show it twice, we should avoid it - please reopen :)

**Comment by sprankhub** [comment]
By default, the short description is not shown twice. We show it in the checkout via MageSetup, but only once. And in Magento, it is normally not shown. If it is shown twice, your template probably includes it as well, so that you can disable the display by MageSetup as explained by @riconeitzel above.
