### ISSUE TITLE
css where i find it

### ISSUE THREAD

**Issue by 4usolutions** [firegento/firegento-magesetup#182]
I must change css settings, because in my theme some parts going wrong.

Where i find the css styls f e.g. the "tax-details"?

**Comment by riconeitzel** [comment]
You should not change the css file of any extension directly. rather use layoutXML to load a custom css file in your theme and straighten the problematic parts.

__app/design/frontend/{package}/{theme}/layout/local.xml__

```xml
<layout>
    <default>
        <reference name="head">
            <action method="addItem"><t>skin_css</t><f>css/custom.css</f></action>
        </reference>
    </default>
</layout>
````
then create ```skin/frontend/{package}/{theme}/css/custom.css``` and use it for CSS.
