### ISSUE TITLE
Standardmäßiges verstecken der Agreements auf BEstellübersichtsseite

### ISSUE THREAD

**Issue by neophilipp** [firegento/firegento-magesetup#185]
Hallo,

kann ich die AGBs, Wiederrufsbelehrungstexte standardmäßig auf "hide" setzen?
Also genau das was passiert wenn man auf "Schliessen" der Texte klickt.

Besten Dank!!!

**Comment by riconeitzel** [comment]
Die Frage verstehe ich leider nicht … Da sind doch nur Links im Review … Was genau möchtest Du denn da verstecken?!
