### ISSUE TITLE
Dynamic Shipping Tax Class Calculation prevents Bundle Products Shipping getting taxed

### ISSUE THREAD

**Issue by jwittorf** [firegento/firegento-magesetup#186]
When using Dynamic Shipping Tax Class Calculation (e.g. use highest rate) there is not tax applied to the shipping when having a bundle product in the cart.
If you have the same product (that's a part of the bundle) as single simple product in the cart, the tax is calculated for the shipping costs.

This is what **should** be calculated:

Subtotal 99,00 €
Shipping 13,99 €
Total 112,99 €
(Included) Tax 18,04 € ((99+13,99)/119*19)

This is what **acutally is** (wrongly) calculated:
Subtotal 99,00 €
Shipping 13,99 €
Total 112,99 €
(Included) Tax 15,81 € (99/119*19)

As you can see, my last calculation misses the "+13,99" from shipping.

Using Magento 1.8.1.0 and MageSetup 2.1.0.

As a quick fix I've set the Dynamic Shipping Tax Class Calculation to none. It’s just a temp fix and only okay because my client doesn’t have multiple tax rates, one should still be able to use the Dynamic Shipping Tax Class Calculation.

**Comment by sprankhub** [comment]
I just checked that and can confirm that this has already been fixed with a3e5c91fd523be043658b53de508d4d17091ae0e.
