### ISSUE TITLE
Individual CMS Pages for Shipping Costs

### ISSUE THREAD

**Issue by margsenjo** [firegento/firegento-magesetup#189]
Hi,
After I've installes MageSetup, the text "incl. 19% tax, zzgl. Versandkosten" routes to /lieferung per default.

However, I want this to be changed to my pre-created CMS pages for Shipping in each store view. Is that easily possible?

Thanks and regards,
Mark

**Comment by riconeitzel** [comment]
It is in system -> configuration -> catalog -> price -> cms page for shipping info


best,
 Rico

**Comment by margsenjo** [comment]
Is it not possible to use 2 different ones for each language store? Otherwise I would have to work with url rewrites which is not a good solution in my opinion

**Comment by riconeitzel** [comment]
basic magento feature: use configuration scopes to configure different pages for different store views!
