### ISSUE TITLE
'Including x% tax excl. Shipping Cost' stated twice on configurable product view page

### ISSUE THREAD

**Issue by margsenjo** [firegento/firegento-magesetup#190]
After installing the Firegento MageSetup and creating configurable products, the text will show twice on each product view page. Please view attachments.

Is this a common problem or can I easily avoid this?
![1](https://cloud.githubusercontent.com/assets/13225151/9394735/70764dc2-478a-11e5-9736-8e210f5dfeb8.PNG)
![2](https://cloud.githubusercontent.com/assets/13225151/9394734/7073cdd6-478a-11e5-8e91-763ea023acf7.PNG)

**Comment by GrafC** [comment]
I had the same issue.
Reason: Amasty colorswatch extension.
Had to set the option: use price for specific products (former: all products)
