### ISSUE TITLE
Translation for Additional Information for storeview

### ISSUE THREAD

**Issue by gino2014** [firegento/firegento-magesetup#191]
Dear community, 
at the magento backend at "system"-"configuration"-"sales"-"checkout"-"checkout configuration" you have the opportunity to add some text for additional information. By default we are using "Beim Versand ins Nicht-EU-Ausland können zusätzlich Zölle, Steuern und Gebühren entstehen." But by changing to our english and greek store view at the backend this point has been gone and we are not able to translate it. Also with translate.csv-file or the inline tool we got no success. Maybe some one found a solution. 
Thanks in advance and for this great extension.

**Comment by riconeitzel** [comment]
I have a fix for that. I'll send it later today. If I forget it please be so kind to send me a reminder. :D

Rico

**Comment by gino2014** [comment]
Hi Rico, 
Thanks you for your quick answer.

**Comment by gino2014** [comment]
Hi Rico,
i just want to remind you for the fix you wanted to send or post.
Thanks in advance and have a nice weekend
Gino

**Comment by riconeitzel** [comment]
Download is available here: [B71a_FixHiddenCheckoutConfig](http://www.buro71a.de/bucket/B71a_FixHiddenCheckoutConfig.zip)

**Comment by mblatt** [comment]
Hallo Rico,

ich habe mir M;agento hier heruntergeladen: http://meet-magento.com/localized-magento-edition/. Dort ist der Fix aber noch nicht integriert, oder sehe ich das falsch?=

Grüße,
Marcus

**Comment by avstudnitz** [comment]
Nein, da ist es nicht enthalten. Das Modul müsste separat installiert werden.

**Comment by mblatt** [comment]
Hallo Andreas,

alles klar. Kann ich denn das aktuelle Modul hier (https://github.com/firegento/firegento-magesetup/archive/2.4.1.zip) herunterladen und bedenkenlos über meinen inzwischen auf 1.9.3.2 aktualisierten Shop drüberbügeln?

Herzliche Grüße,
Marcus

**Comment by avstudnitz** [comment]
Ja, das geht normalerweise problemlos so.

**Comment by mblatt** [comment]
Perfekt, dann löst sich sicher auch das Problem, dass meine MagentoDE-Übersichtsseite seit dem Update mit Patches einen 404er ausgibt ?

Herzliche Grüße,
Marcus

**Comment by mblatt** [comment]
Guten Abend Andreas,

ich habe nun die neueste Version 2.4.1 installiert, Caches gelöscht und mich ein- und wieder ausgeloggt. Leider sehe ich den Punkt "zur Kasse" nicht im englischen Store-View. Ich dachte der Fix wäre in der neuesten Version drin?

Herzliche Grüße, Marcus

**Comment by Schrank** [comment]
@mblatt Ich fürchte du hast was missverstanden.

> Nein, da ist es nicht enthalten. Das Modul müsste separat installiert werden.

Heißt nicht, dass es im aktuellen drin ist, sondern dass du das Modul von @riconeitzel extra installieren musst.

**Comment by mblatt** [comment]
ah, also den Fix http://www.buro71a.de/bucket/B71a_FixHiddenCheckoutConfig.zip. Richtig?

**Comment by Schrank** [comment]
Genau

**Comment by mblatt** [comment]
ah, perfekt, hat geklappt. Vielleicht darf ich noch eine abschließende Frage stellen: ich hatte mir die localized MagentoDE (1.9.2.4 vom 03.06.2016) heruntergeladen und installiert. Nach dem Upgrade auf 1.9.3.2 bzw. Einspielenaller aktuellen Patches über die normale Magento-Seite erhalte ich im backend bei den Unterseiten von MagentoDE "Übersicht", "Partner", "Empfehlungen", "Paypal-Express konfigurieren" und "Support Center" einen 404er. Hat das mit einem der SUPEEs und <use>admin</use> zu tun?
