### ISSUE TITLE
Caching Problem im Checkout mit den Agrements/caching problems on checkout agreements

### ISSUE THREAD

**Issue by easyMaxi** [firegento/firegento-magesetup#192]
HI,

http://shopurl/magesetup/frontend/agreements/id/1/
and http://shopurl/magesetup/frontend/agreements/id/2/ (agreements on checkout)
always show the same content.  If I call 1 first, then 2 has the same content as 1 and the other way around. I can empty the cache and this way i can change what is shown.
Magent 1.9.2. Can anyone reproduce this?

------

Am Ende es Checkouts zeigen beide Agreement Popups die gleichen Inhalte an.
http://shopurl/magesetup/frontend/agreements/id/1/ und http://shopurl/magesetup/frontend/agreements/id/2 sind die Links. Eigentlich AGB und Widerruf. Abhängig davon welche Seite ich nach einem leeren der Caches aufrufe, ist der Inhalt der beiden festgelegt.
Magento 1.9.2. Kann das bitte einer bei sich überprüfen und mir sagen, ob das Problem auch bei ihm auftritt?

**Comment by riconeitzel** [comment]
Das ist ein magento bug. Such mal nach "192 cms cache bug magento". Ich bin leider grad nur mobil unterwegs, aber es gibt eine Lösung via Observer.

Viele Grüße rico

**Comment by easyMaxi** [comment]
Oh, super vielen Dank für die Info.
Ich probiere das mal aus und melde mich, wenn ich eine funktionierende Lösung habe. Dann kann da noch wer anders von profitieren.
