### ISSUE TITLE
No tax info for bundle products - intentionally?

### ISSUE THREAD

**Issue by infabo** [firegento/firegento-magesetup#194]
In class FireGento_MageSetup_Block_Bundle_Catalog_Product_Price the following method does return an empty tax-rate if the product type is of type "bundle".
Is this by design or should it rather be "grouped"? By Magento default bundle-products do have a tax_class_id, therefore it should be possible (IMHO) to calculate the tax_rate for bundles.
I'm a bit confused.

https://github.com/firegento/firegento-magesetup/blob/master/src/app/code/community/FireGento/MageSetup/Block/Bundle/Catalog/Product/Price.php#L79

```
 /**
     * Retrieves formatted string of tax rate for user output
     *
     * @return string Formatted Tax Rate for the given locale
     */
    public function getFormattedTaxRate()
    {
        if ($this->getTaxRate() === null
            || $this->getProduct()->getTypeId() == 'bundle'
        ) {
            return '';
        }

        $locale = Mage::app()->getLocale()->getLocaleCode();
        $taxRate = Zend_Locale_Format::toFloat($this->getTaxRate(), array('locale' => $locale));

        return $this->__('%s%%', $taxRate);
    }
```

Could someone enlighten me? :)

**Comment by luckyduck** [comment]
I can confirm that the tax info is missing for bundled products. Simply modifying the if-statement doesn't help, though.

**Comment by Schrank** [comment]
Before we implement this, we need to know, what to implement, see #186

**Comment by Schrank** [comment]
What is the tax class for bundle products with mixed taxes?

**Comment by infabo** [comment]
Good question

**Comment by Detzler** [comment]
It doesn't matter what kind of articles are inside the bundle product. It's just a backend question.
From the frontend (buyers) point of view, the bundle product is just a "simple product" that contains stuff.
The merchant is responsible to mark this product with the right tax class. 
MageSetup shouldn't deliver any automatism for the tax classes of bundle products.

**Comment by Detzler** [comment]
@infabo Did you find out how to enable the block on bundle product pages?

**Comment by Schrank** [comment]
Unfortunately not. You cannot configure a tax class for a product:

![bildschirmfoto 2015-11-12 um 18 40 31](https://cloud.githubusercontent.com/assets/379680/11126000/2fd6b638-896d-11e5-925b-6f6c8bc480aa.png)

It is just greyed out.

**Comment by Schrank** [comment]
So the tax class is the one from the simple items - which might have different ones. In Germany this can be 0%, 7% and 19% which is horrible. It is the same horrible as for shipping.

**Comment by infabo** [comment]
ok. seems like it's time for a PR ;)

**Comment by Schrank** [comment]
Maybe I'm too dumb, but how to configure a fixed tax class on a bundle product?

**Comment by Detzler** [comment]
If the price is set to be fixed (selectbox near price attribute) then the tax class is applicable in the backend. So MageSetup should show the block as like as at the simple product.

Otherwise it's dynamic. That's what @Schrank means.
How to show the block then?

This law office says that it's not required to print the exact amount of the tax at the german market.
It's just enough to say "inkl MwSt".
https://www.it-recht-kanzlei.de/Thema/preisangabenverordnung.html?page=2#sect_4

**Comment by Schrank** [comment]
Be careful. What they say is IF (and only if) there is **no** `add to cart` button, THEN we don't have to print anything.

**Comment by sprankhub** [comment]
My latest commit ensures that the tax rate is shown for bundle products with fixed pricing.

We could at least improve the tax rate display for bundle products with dynamic pricing like this:

1. If all associated child products have the same tax rate, show this tax rate.
2. If they have different tax rates, do not show any exact tax rate.

We should just be careful that the retrieval of the child products is performant.

**Comment by Schrank** [comment]
I'll open a new issue for the dynamic bundles to keep it cleaner.
