### ISSUE TITLE
Change link of checkout agreements

### ISSUE THREAD

**Issue by margsenjo** [firegento/firegento-magesetup#195]
Hi,
Is it possible to change the checkout agreement links (show) to a cms page which will be opened in a blank target instead of the small windows with the blocks? I have tried it, but both links always referred to the same page.

thanks, regards

**Comment by riconeitzel** [comment]
Is your problem related to this, because you still use 1.9.2.0? (See last two links) -

**Comment by riconeitzel** [comment]
https://github.com/firegento/firegento-magesetup/issues/192

**Comment by margsenjo** [comment]
it's not really a problem, and i use 1.9.2.1. the windows show different content. however i want the links to refer to my specific cms pages if thats possible. i couldnt find a way to work that out yet though.

**Comment by riconeitzel** [comment]
you can change the text of your checkout agreements from 

```
{{block type="cms/block" … }}

```

to something like

```
{{block type="cms/page" page_id="xxx"}}
```

with xxx having your page_id value.

Rico
