### ISSUE TITLE
Product Prices index process unknown error

### ISSUE THREAD

**Issue by balters** [firegento/firegento-magesetup#196]
Hallo, seit der Installation baut der Preis Index nicht mehr auf.
Ich bekomme folgende Meldung:
>
Product Prices index process unknown error:
exception 'PDOException' with message 'SQLSTATE[21S01]: Insert value list dös not match column list: 1136 Column count doesn't match value count at row 1' in /var/www/vhosts/.../.../shop/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /var/www/vhosts.../.../shop/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /var/www/vhosts/.../.../shop/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /var/www/.../.../shop/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /var/www/vhosts/.../.../shop/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#4 /var/www/vhosts/.../.../shop/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array)
#5 /var/www/vhosts/l.../.../shop/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ca...', Array)
#6 /var/www/vhosts/.../.../shop/app/code/community/OrganicInternet/SimpleConfigurableProducts/Catalog/Model/Resource/Eav/Mysql4/Product/Indexer/Price/Configurable.php(133): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ca...')
#7 /var/www/vhosts/.../.../shop/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price/Configurable.php(48): OrganicInternet_SimpleConfigurableProducts_Catalog_Model_Resource_Eav_Mysql4_Product_Indexer_Price_Configurable->_prepareFinalPriceData()
#8 /var/www/vhosts/.../.../shop/app/code/core/Mage/Catalog/Model/Resource/Product/Indexer/Price.php(385): Mage_Catalog_Model_Resource_Product_Indexer_Price_Configurable->reindexAll()
#9 /var/www/vhosts/.../.../shop/app/code/core/Mage/Index/Model/Indexer/Abstract.php(143): Mage_Catalog_Model_Resource_Product_Indexer_Price->reindexAll()
#10 /var/www/vhosts/.../.../shop/app/code/core/Mage/Index/Model/Process.php(212): Mage_Index_Model_Indexer_Abstract->reindexAll()
#11 /var/www/vhosts/.../.../shop/app/code/core/Mage/Index/Model/Process.php(260): Mage_Index_Model_Process->reindexAll()exAll()
#12 /var/www/vhosts/.../.../shop/shell/indexer.php(167): Mage_Index_Model_Process->reindexEverything()
#13 /var/www/.../.../shop/shell/indexer.php(215): Mage_Shell_Compiler->run()
#14 {main}

Ich habe von German Setup auf megasetup gewechselt. Emails werden seit dem auch keine mehr vom Shop versandt 

Magento Version 1.9.1.1

**Comment by balters** [comment]
Hallo noch mal, nachdem ich OrganicInternet_SimpleConfigurableProducts deinstalliert habe lässt sich der Index wieder aufbauen.

Leider werden weiterhin keine Bestellbestätigung gesandt.
Die Willkommenemail hingegen wird ordnungsgemäß versandt.

Nach wie vor würde ich mich über Hilfe freuen.

**Comment by riconeitzel** [comment]
Hi,

Magento sendet seit 1.9. Mails per cron Job. Läuft der bei dir? 

Liebe Grüße Rico

**Comment by balters** [comment]
Guter Hinweis. Wie genau kann ich das prüfen?
Hinweis: Vor der Installation wurden die Mails Versand. Die Willkommensemail wird Versandt. Ist das unabhängig?

**Comment by riconeitzel** [comment]
Das weiss ich nicht auswendig, ich denke, dann dürfte der CronJob laufen.

Hmmm was steht in den Dateien in var/log/ drin? Ein Hinweis auf das Problem?

Ist es ein Livesystem oder ein Testsystem?

Viele Grüße Rico

**Comment by balters** [comment]
Leider ist anhand der Log Dateien nichts zu erkennen. 

der letzte Eintrag ist: Permission denied: file permissions deny server access: /var/www/.../.../shop/app/etc/local.xml

Das folgende traue ich mich nicht zu sagen ;( ist ein Livesystem

**Comment by balters** [comment]
Ich nehme alles zurück und behaupte das Gegenteil. Es lag an den  CronJob! Danke für deine Hilfe!

schönen Abend noch
