### ISSUE TITLE
Steuer-Einstellungen not saved

### ISSUE THREAD

**Issue by githubertus** [firegento/firegento-magesetup#198]
Whatever I chose, I'm ending up with "Vollbesteuerte Artikel" after running MageSetup
![vollbest](https://cloud.githubusercontent.com/assets/9904364/9931348/384316a8-5d3b-11e5-81a0-dcec53bb1a17.png)

Magento 1.9.2.1
MagSetup 2.2.3

**Comment by avstudnitz** [comment]
You can ignore whatever is displayed there after having run MageSetup. It's just a setting for the _next_ setup run. Only the tax classes which are assigned to the products matters. This setting isn't used anywhere except when executing MageSetup (which will usually be done just once).
