### ISSUE TITLE
disable delivery time (Lieferzeit) on product detail page

### ISSUE THREAD

**Issue by mrafulfill** [firegento/firegento-magesetup#200]
It would be great if it was possible to configure the visibility of the delivery time attribute on the product detail page. We are using a more advanced solution for delivery time and therefore want to disable the MageSetup delivery_time attribute on the product detail page. Can you suggest the easiest way to disable delivery_time in the code?

**Comment by Rogier076** [comment]
I was looking for exactly te same. I was not able to find the setting anywhere. Checked some layout files but could not find it there either. The I found out that the controller that displays the delivery time checks if the attribute 'delivery_time' exists. If not, it is not being displayed.  I removed the attribute 'delivery_time' in magento and now it is not visible on the product detail page anymore.

**Comment by akkermanronald** [comment]
Hi Rogier076,

We have modified the layout xml but it would be easier to have this as a configurable setting, see below for others that may need this:

![schermafdruk 2015-11-06 11 55 46](https://cloud.githubusercontent.com/assets/15016164/10995492/93c7576e-847d-11e5-97d9-ffbd312f1bb0.png)

**Comment by sprankhub** [comment]
This is already implemented. See System > Configuration > Catalog > Price > Display Delivery time on Product Detail.
