### ISSUE TITLE
Visible in Checkout - can not switch over to "yes"

### ISSUE THREAD

**Issue by galaxist740** [firegento/firegento-magesetup#203]
Hi!,
i get an error message with "Column not found: 1054 Unknown column 'additional_table.is_visible_on_checkout'......". In Database the column does not exist. 

When i would change an attribute to make it visible in checkout I can't switch over to "yes". After I save with "yes" the dropdownlist shows me "no"! Probably why the column is missing. 

This error is in Magento version 1.9.2.1 Firegento magesetup <version>2.2.3</version>

How can I get the column?

**Comment by riconeitzel** [comment]
You can disable the caches in magento, reset the core_resource entry for "firegento_magesetup" to 2.1.1 and reload the frontend. It's a bug we think and it already has a ticket #199.
