### ISSUE TITLE
MwSt. Anzeige in Kategorieansicht ausblenden

### ISSUE THREAD

**Issue by niceart** [firegento/firegento-magesetup#204]
Hallo!

gibt es eine Möglichkeit in der Kategorieansicht die Erweiterung MwSt und Versandkosten auszublenden? Problem ist dass bei Gruppenartikeln 0% MwSt. angezeigt werden und das ja nicht stimmt.

Wenn ja, wie können wir das machen?

Danke vorab!
Andreas

**Comment by niceart** [comment]
Hallo! 
hat jemand eine Idee und kann mir helfen?
Danke.
Gruss
Andreas

**Comment by DevertNet** [comment]
+1 "bei Gruppenartikeln 0% MwSt. angezeigt"

**Comment by sprankhub** [comment]
Um den Hinweis auf den Kategorieseiten auszublenden, schau dir mal das hier an: https://github.com/firegento/firegento-magesetup/issues/68#issuecomment-43995552

**Comment by Schrank** [comment]
Das ist die einfache Lösung, der Observer die schönere, wenn ihr mich fragt: https://github.com/firegento/firegento-magesetup/issues/68#issuecomment-69617298

**Comment by Schrank** [comment]
Blöde Frage am Rande: Was ist der Steuersatz eines Bündelprodukts mit gemischten Steuersätzen?

**Comment by sprankhub** [comment]
@Schrank ich habe genau auf die Observer-Lösung verlinkt, aber naja ^^ Gute Frage, was da der korrekte Steuersatz ist. Jemand einen Steuerberater zur Hand, der das beantworten kann?

**Comment by XSized** [comment]
Um das nochmal hoch zu wühlen - hab den verlinkten Observer getestet, bin aber offensichtlich nicht fit genug im Thema Erweiterungen erstellen. Könnte das mal bitte jemand etwas detaillierter ausführen? Scheint mir nur halber oder Pseudocode zu sein.

**Comment by Schrank** [comment]
Du meinst 

    /**
     * @mageEvent magesetup_after_product_price
     * 
     * @param type $event
     */
    public function removeMageSetupPriceHint($event)
    {
        if(in_array('catalog_category_view', Mage::app()->getLayout()->getUpdate()->getHandles()) || in_array('catalogsearch_result_index', Mage::app()->getLayout()->getUpdate()->getHandles())
        {
            $obj = $event->getHtmlObj();
            $obj->setPrefix('');
            $obj->setHtml('');
            $obj->setSuffix('');
        }
    }
            <magesetup_after_product_price>
                <observers>
                    <kitchenking>
                        <class>custom/observer</class>
                        <method>removeMageSetupPriceHint</method>
                    </kitchenking>
                </observers>
            </magesetup_after_product_price>

Da ist alles was du brauchst, das Event, der eintrag in der config.xml (der gehört in die frontend node) und die methode im Observer selbst.

Möglicherweise ist dein Problem gut auf http://magento.stackexchange.com aufgehoben?

**Comment by XSized** [comment]
Genau das meinte ich. Speziell die config.xml hab ich offenbar nicht korrekt... ich schau mal. Danke
