### ISSUE TITLE
SUPEE-6788 Compatibility

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-magesetup#207]
Since the `cms/block` block is used by the the locale templates under https://github.com/firegento/firegento-magesetup/blob/master/src/app/locale/de_DE/template/magesetup, it should be added to the new whitelist. This should be done with a new version and a upgrade script similar to [this one](http://magento.stackexchange.com/a/87974/142).

There may be some other values/blocks which have to be whitelistet (?). Here is a first list with the values I found:

Blocks:
- `cms/block`
- `magesetup/imprint_field`
- `magesetup/imprint_content`

**Comment by sr972** [comment]
Slightly OT, but:
Did you get magesetup 2.2.2 working on 1.9.2.2 and/or with SUPEE-6788?
I've updated a dev system to 1.9.2.2 but as there is just v2.2.2 on MCM i don't get it worked by now as soon as i deactivate comp mode in backend.

Did you just update the files by yourself to v2.2.3?

**Comment by sprankhub** [comment]
You have to use 2.2.3 with Magento 1.9.2.2. Yeah, of course I updated "manually" - using a version control system (git).

**Comment by sr972** [comment]
I know git ;)
Just still wondering that nothing happens to magesetup on MCM as there is a build error and no regular update on MCM. My customer has strict settings e.g. just using stables from MCM and so on.

**Comment by sprankhub** [comment]
2.2.3 is officially [tagged](https://github.com/firegento/firegento-magesetup/releases) on GitHub, so you should be good to go.

Anyway, feel free to open a new issue asking for a Magento Connect release. Let us stick to the base topic here.

**Comment by klein0r** [comment]
Check branch fix_sup6788

**Comment by Schrank** [comment]
As @sprankhub correctly listed, `cms/block` is still missing.

**Comment by klein0r** [comment]
Ooops... I thought cms/block was already added by the new setup which creates the permission tables.

**Comment by Schrank** [comment]
I only see `core/template` and `catalog/product_new` everywhere. But didn't check the source, anyone? :D

**Comment by Schrank** [comment]
Fixed with #219

**Comment by niceart** [comment]
hello, wo patched a 1.7.0.2 version - how can we add the blocks to the whtielist. there are no tables in the database? the blocks are not visible. please help us!

**Comment by sprankhub** [comment]
If there are not the right tables in the database, you did not properly apply the patch or did not properly clear the cache. You can whitelist the blocks in the admin area under System - Permissions - Blocks/Variables.
