### ISSUE TITLE
Keine E-Mails nach Update auf 1.9.2.2

### ISSUE THREAD

**Issue by KlausGw** [firegento/firegento-magesetup#217]
Nach dem Update auf 1.9.2.2 werden keine E-Mails mehr gesendet.
Unter System - Berechtigungen - Block sind diese beiden Blöcke definiert:
magesetup/imprint_field
magesetup/imprint_content

Magesetup ist 2.2.3

Es gibt unter /logs auch keine Fehlermeldungen.

Kann es sein, dass noch bestimmte Variablen auf die Whitelist müssen?

**Comment by sprankhub** [comment]
Wie kommst du darauf, dass es mit MageSetup zu tun hat? :) ich nehme an, dass dein Cronjob nicht mehr richtig funktioniert. Ggf, weil dieser per HTTP aufgerufen wurde und das mit 1.9.2.2 gesperrt wurde...

**Comment by riconeitzel** [comment]
Hallo Klaus,

hattest du vorher schon Magento 1.9.x im Einsatz? Der CronJob MUSS jetzt zwingend laufen, da die E-Mails seit 1.9.x via CronJob gesendet werden.

Ergo: Kein CronJob -> keine E-Mails.

Liebe Grüße
 Rico

**Comment by KlausGw** [comment]
Hallo Simon, hallo Rico,

vielen Dank für die schnellen Antworten.

Ich hatte vorher 1.9.2 im Einsatz und habe jetzt das Update gefahren auf 1.9.2.2.

Der Cronjob wird so aufgerufen:
wget -O - -t 1 -q http://www.domainxyz.de/testshop/cron.php

Wie müsste es denn richtig sein?

LG
Klaus

**Comment by riconeitzel** [comment]
Hi …

bei welchem hoster bist du? Normalerweise nutzt man die Bash-Script Version:

/pfad/zum/account/und/zu/magento/cron.sh

Alternativ ginge noch die PHP via

php -- -f /pfad/zum/account/und/zu/magento/cron.php

oder bei mittwald:
php_cli -- -f /pfad/zum/account/und/zu/magento/cron.php

die SH Version ist aber zu bevorzugen, damit die CronJobs nicht kaskadieren. Aufruf-Abstand MINDESTENS alle 5 Minuten, besser minütlich.

Liebe Grüße
 Rico

**Comment by KlausGw** [comment]
Rackspeed

**Comment by Schrank** [comment]
Hi Klaus,

wir Rico und Simon schon korrekt sagten hast du den Cronjob via http aufgerufen. Das musst du ändern zu einem aufruf via bash.

Eine Erklärung gibt es bei den webguys: http://www.webguys.de/magento/adventskalender/turchen-15-cronjobs-im-magento/

**Comment by Schrank** [comment]
Achso, um die Frage vom anfang zu beantworten: JA, man muss blöcke whitelisten. Das tut die Version 2.3.0 (sobald sie draußen ist). Wenn du experimentierfreudig bist, darfst du gerne den devlop branch benutzen.

**Comment by Schrank** [comment]
(wobei da auch noch ein Block fehlt)

**Comment by KlausGw** [comment]
Ich bekomme jetzt immer die Fehlermeldung: keine Berechtigung.
Hab schon alles mögliche ausprobiert (644, 666, 766, 777)
Weiß jemand, wie die Rechte bei Rackspeed sein müssen?

**Comment by riconeitzel** [comment]
Wende Dich mal an deren Support … die sind gut und schnell und können Dir besser weiterhelfen als wir :-)

Liebe Grüße
 Rico

**Comment by Schrank** [comment]
@KlausGw Das könnte helfen: https://github.com/OpenMage/magento-mirror/blob/1.9.2.2/.htaccess#L211-L234 einfach alles auskommentieren und dann sollte es wieder gehen, aber frag mich nicht, was die Seiteneffekte sind.

**Comment by KlausGw** [comment]
Hello!

 

New message, please read <http://thoitrangtruongsy.com/compete.php?jp>

 

info@gwiasda.eu

**Comment by KlausGw** [comment]
Hey,

I've got some good news for you, read more about it here <http://spycunkytri.vahaug.com/lnolzrjm>

info@gwiasda.eu

**Comment by KlausGw** [comment]
Hello,

There are a cople of stories I wanted to share with you, please, read more here <http://sloslilate.fwccharters.com/lntnxwsj>

Yours faithfully, info@gwiasda.eu
