### ISSUE TITLE
Remove outdated infos from header

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-magesetup#218]
``` php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_MageSetup
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2013-2015 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 * @version   2.2.2
 * @since     0.1.0
 */
```

I would recommend to remove:

``` php
 * PHP version 5
 *
 * @version   2.2.2
 * @since     0.1.0
```

And the years from `@copyright`. All the infos are outdated all the time and only costs time to keep updated for no benefit.

**Comment by sprankhub** [comment]
:+1: 

The [coding guidelines](https://github.com/firegento/coding-guidelines/blob/master/guidelines/02_CODE_DOCUMENTATION.md) also do not mention `@version` and `@since`. They mention the PHP version though.

**Comment by therouv** [comment]
`@version` and `@since` can be removed in my opinion.

**Comment by avstudnitz** [comment]
+1

**Comment by sprankhub** [comment]
I removed `@version` and `@since` from the file headers. Since `PHP version 5` and the copyright year is part of the [coding guidelines](https://github.com/firegento/coding-guidelines/blob/master/guidelines/02_CODE_DOCUMENTATION.md), I would stick with them. We can of course update the coding guidelines and change it afterwards.
