### ISSUE TITLE
Nach Installation -> Frontend-Probleme

### ISSUE THREAD

**Issue by emamil** [firegento/firegento-magesetup#220]
Hallo,

würde mich freuen, wenn mir einer weiterhelfen könnte.
Nach der Installation von Mage Setup, habe ich große Schwierigkeiten auf der Frontend-Seite gehabt.
Außer der Hauptseite konnte ich keine anderen Links mehr erreichen, weder die Produkte noch die Kategorien.
Hätte da jemand eine Idee, dies zu umgehen oder dieses Problem zu beseitigen?

Vielen Dank

Emamil

**Comment by Schrank** [comment]
Hi Emamil, kannst du bitte ein wenig ausführen was dein Problem genau ist? Ein Link, ein Screenshot. Was meinst du mit "geht nicht mehr"

**Comment by emamil** [comment]
Hi Schrank, sry für die späte Antwort.
Mit "geht nicht mehr" meine ich, dass man auf dem Frontend außer der Startseite keine andere Seite erreichen kann. Zum Beispiel die Kataloge, die Produkte oder den Warenkorb. Man klickt auf einen Artikel auf der Startseite und es zeigt nur noch an, dass es die Seite lädt. Jedoch öffnet sie nicht.
Mittlerweile habe ich das Mage Setup wieder deinstalliert, damit die anderen Seiten erreichbar bleiben.

Meine Frage wäre, ob das was mit der Performance zu tun hat? Wenn du da Tippst hättest, würde ich mich sehr freuen.

**Comment by riconeitzel** [comment]
Ich schätze, du hast nach dem Setup weder die Caches gelöscht noch die Indizes neu aufgebaut, oder?

**Comment by emamil** [comment]
Hi Rico, doch habe ich. Ich kenne mich leider noch nicht sehr viel mit Magento aus, aber ich dachte das System wäre irgendwie überlastet.

**Comment by Schrank** [comment]
MageSetup tut eigentlich "nichts", es bindet ein paar Blöcke ein, ein paar Layout updates, eine system.xml aber effektiv nichts, was wirklich lange dauert.

Das was du beschreibst macht eigentlich keinen Sinn und sollte sich evtl. mal ein Profi ansehen. Ich fürchte das ist ein lokale Problem.

**Comment by emamil** [comment]
h

**Comment by emamil** [comment]
Wenn es Sinn machen würde, wäre es ja auch kein Problem.
Danke für die Antwort.

**Comment by sprankhub** [comment]
Nur noch ein kleiner abschließender Hinweis abseits von Cache aktualisieren und Indexe neu aufbauen: Unbedingt auch den Compiler abschalten.

**Comment by emamil** [comment]
Werde ich beachten, danke Simon.
