### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-magesetup#223]
Magento removed their files from:

http://www.magentocommerce.com/downloads/assets/1.6.2.0/magento-1.6.2.0.tar.gz

so we have to use the new(?) api to get magento source:
http://magento.stackexchange.com/a/58031/217

or maybe just a github mirror, like:
https://github.com/OpenMage/magento-mirror/archive/1.9.2.1.zip

But to use any of these, we have to patch https://github.com/EcomDev/MageCI

**Comment by sprankhub** [comment]
Fixed in development branch with https://github.com/firegento/firegento-magesetup/commit/745445eb1002fc1ec4b49d317776e7caf55ec39f.
