### ISSUE TITLE
Blocktype permissions (1.9.2.2)

### ISSUE THREAD

**Issue by Julime** [firegento/firegento-magesetup#226]
Since 1.9.2.2 Block Types need to be allowed in backend:
http://magento.stackexchange.com/questions/88117/cms-blocks-disappeared-after-1-9-2-2-update

Mabe there is a way to add them automatically?

**Comment by sprankhub** [comment]
This is already solved. See https://github.com/firegento/firegento-magesetup/issues/207 / https://github.com/firegento/firegento-magesetup/pull/219.
