### ISSUE TITLE
update auf magento 1.9.2 von 1.9.1

### ISSUE THREAD

**Issue by stradd** [firegento/firegento-magesetup#227]
Ich habe von einen Update vonmagento 1.9.1 auf 1.9.2.2 gemacht. danach werden die Inhalte die Magesetup hinzufügt z.B- {{block type="cms/block" block_id="gs_business_terms"}} nicht mehr angezeigt. Unter cms -> Seiten steht der obige Inhalt und unter cms -> statische Blöcke ist auch der alte Inhalt zu sehen. Das Problem triftt auf alle anderen Seiten zu z.B.
{{block type="magesetup/imprint_content" template="magesetup/imprint/address.phtml"}}
{{block type="magesetup/imprint_content" template="magesetup/imprint/communication.phtml"}}
 {{block type="magesetup/imprint_content" template="magesetup/imprint/legal.phtml"}}

Ich habe vesrucht magesetup neu zu starten und neu zu installieren und neu zu starten hat leider nicht geholfen. Magento Cache habe ih geleert.

Woran könnte das liegen?

Gruss Stradd

**Comment by Schrank** [comment]
Das Problem ist gelöst in Version 2.3.1, leider ist die noch nicht releaset. Zieh dir den develop branch, sei vorsichtig damit, teste ordentlich und werde glücklich :-)

**Comment by stradd** [comment]
Vielen Dank für die Info werde es so machen
