### ISSUE TITLE
Create rewrites for germansetup cms blocks used in emails

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-magesetup#230]
Just an idea, what happens if we create rewrites for the three blocks, german setup uses in emails:

    germansetup/imprint_content
    germansetup/imprint_field

Then we don't have to update all emails after an update.

Any downside on this? Except having three lines of legacy in the config.xml.

Pros? Cons?

**Comment by sprankhub** [comment]
I don't think that you want to rewrite `cms/block`. 

It probably drops the quality scores which come out of static code analysing tools, but I do not really care...

**Comment by Schrank** [comment]
Thanks, removed it. Of course not :-) I only want to create downwards compatibility for parts which take huge afford to update.

**Comment by riconeitzel** [comment]
Wie wäre es alternativ mit einem Update für GermanSetup? Wir dependen dann auf MageSetup und extenden einfach klassen von MageSetup? Dann wäre es quasi das letzte update dafür und damit stellen wir eine Umleitung bereit!?

**Comment by Schrank** [comment]
auch schön, dann kann man einfach magesetup installieren und es läuft gemeinsam

**Comment by sprankhub** [comment]
Nicht wirklich, weil MageSetup GermanSetup explizit deaktiviert...

**Comment by Schrank** [comment]
Blöd gesagt, das ließe sich umgehen indem wir in der aktuellsten Version von Germansetup auf MageSetup dependen und es wieder anmachen. Aber so richtig geil ist das alles nicht.

**Comment by riconeitzel** [comment]
Also brauchen wir einen Supporter, der Fixes für GermanSetup backported? :D
