### ISSUE TITLE
SUPEE-6788 changes admin version only slightly in 1.5.0.1

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-magesetup#231]
we have in our script:

```
if (version_compare($adminVersion, '1.6.1.1', '>')) {
```

which works for versions > 1.6 but not in 1.5, where admin version is changed to 0.7.2.1.2

**Comment by sprankhub** [comment]
The [README](https://github.com/firegento/firegento-magesetup#compatibility) states that we only support Magento >= 1.6. Hence, I think we can ignore this issue. I would highly recommend to update your shop ;-)
