### ISSUE TITLE
Steuern innerhalb von D, innerhalb EU, außerhalb EU.

### ISSUE THREAD

**Issue by wompip** [firegento/firegento-magesetup#232]
Mein (reiner) B2B Shop hat den Sitz in Deutschland. Bei Kunden in Deutschland wird korrekt USt. ausgewiesen, bei Kunden außerhalb der EU (korrekterweise) nicht.
Problem: bei Kunden, die z.B. in Frankreich registriert sind, wird ebenfalls USt. ausgewiesen. Dort soll logischerweise keine ausgewiesen werden, weil sie keine bezahlen. UST-ID ist vorhanden.
Welche Einstellungen muss ich vornehmen, damit das korrekt funktioniert?

**Comment by Schrank** [comment]
Reden wir von registrierten Kunden und Kundengruppen? Meines wissens nach funktioniert das nur mit selbigen, denn die Steuerklasse hängt von der Kundengruppe ab. Kein Kundenkonto, keine Steueränderung.

Für "neue" Kundenkonten, die sich während des Checkouts anmelden, geht das noch nicht, erst beim zweiten Mal, wenn sie in der richtigen Gruppe gelandet sind, die entsprechend konfiguriert ist.

Das kann Magento auch nicht. Die Kollegen von Sitewards haben da was, was das tun könnte, weiß ich aber nicht: https://github.com/sitewards/B2BProfessional

**Comment by Schrank** [comment]
Gerne antworten, ich mach das Ticket auch wieder auf, wenn es was zu tun gibt!

**Comment by wompip** [comment]
Ja, wir reden von registrierten und bestätigten Kunden. Ich habe diebezüglich keinerlei Kundengruppen angelegt, weil ich es so verstanden hatte, dass magesetup diese UST-Berechnung automatisch herstellt (aufgrund des Landes des registrierten Kunden). Zumindest scheint ja irgendwas automatisch zu gehen - denn Kunden aus Drittländern bekommen keine UST ausgewiesen, deutsche Kunden schon. Beides ist korrekt. Nur EU-Kunden funktionieren nicht richtig.
Ist das gar keine Angelegenheit von magesetup?
Zusatzfrage: Ist magesetup für einen reinen (deutschen) B2B-Shop eventuell vollständig unnötig?
Sorry, wenn ich zu dusselig bin...

**Comment by Schrank** [comment]
Ich habe keinen 100% Überblick über die Feature, aber meiner Meinung nach fügt es nur Informationspflichten, etc. hinzu die für B2C wichtig sind.

Und erzeugt Emails, CMS-Blöcke und Steuersätzen (die vermutlich für alle wichtig sind)

Aber zurück zu der Frage:
Das was du möchtest hat nichts mit MageSetup zu tun, sondern macht Magento von sich aus. Du kannst eine Kundengruppe anlegen, dieser Kundengruppe sagen, dass sie keine Steuern bezahlen muss (Kundensteuerklasse) und zusätzlich Magento anweisen, wenn ein Kunde bei der Registrierung eine valide VAT-ID hat, ihn in diese Gruppe zu stecken. Das sollte dein Problem lösen.

**Comment by wompip** [comment]
Ok, dann blicke ich jetzt etwas mehr durch als vorher ;-)
Danke!
