### ISSUE TITLE
Terms and Conditions URL is redirected to Shop-Base url when SSL activated

### ISSUE THREAD

**Issue by itsolon** [firegento/firegento-magesetup#233]
We have a Multistore. Everything worked fine.

Now we added SSL cert for all our storeviews.

During checkout you have to accept terms and conditions. That works but if you want to view them
the wrong Content is shown , first of all i thought it is a Problem with the id, but id is right, the wrong static block is loaded because of wrong URL

for example:

base-url.com (shopinstallation)
some-domain.com (storeview)
http://www.some-domain.com/magesetup/frontend/agreements/id/4/  Redirects to 
http://base-url.com/magesetup/frontend/agreements/id/4/

and thats the wrong storeview

the Problem is that Terms and conditions URL for popup window should be https then everything is fine!

how can i achieve that?

**Comment by Schrank** [comment]
Sounds like a bug in one of the templates. But if this would be the case, some one else would have reported it. So I think some one has to look into it. Not sure, when we will find time for it. If you need it faster, I recommend to get one of the contributors to have a look on it.

**Comment by itsolon** [comment]
Solved:
We have found out how to manage this Problem:
we had activated "Admin routing compatibility mode for extensions" new function of SUPEE 6788
now we have updated all extensions to be compatible with new behaviour of Magento and could deactivate this Option.
Now it works as expected
Best Regards 
Markus

**Comment by Schrank** [comment]
Great to hear, thanks for the report!
