### ISSUE TITLE
"0% Tax" in search results

### ISSUE THREAD

**Issue by duke-** [firegento/firegento-magesetup#234]
$this->getFormattedTaxRate() in price_info.phtml always returns "0%" within search results.

My (really quick & dirty) workaround:
FireGento/MageSetup/Block/Catalog/Product/Price.php line 225
`//$taxClassId = $product->getTaxClassId();`
`$taxClassId = Mage::getModel( 'catalog/product' )->load($product->getId())->getTaxClassId();`

#worksforme ;)

-- Michael

**Comment by Schrank** [comment]
NEVER load an EAV model to get a single attribute. Instead make sure that the attribute is loaded together with the collection.

I'm not sure whether "use in product list" for an attribute is enough, in worst case, you need to find a suitable event and add the attribute BEFORE loading.

That said, this has nothing to do with magesetup.
