### ISSUE TITLE
Agreements Blocks werden nicht mehr angezeigt

### ISSUE THREAD

**Issue by margsenjo** [firegento/firegento-magesetup#235]
Hallo,
ist es möglich, die CMS Blocks für die Agreements im checkout zu ändern? Seit heute werden mir in den Popups leere Flächen angezeigt, obwohl die Blocks 'revocation' und 'business_terms' wie gehabt gefüllt sind.
Ich habe nicht herausfinden können, die die id's festgelegt werden (momentan agreements/id/1 und /id/2).

**Comment by Schrank** [comment]
Wenn ich raten müsste würde ich sagen, du hast den Patch SUPEE-6788 installiert ohne die Blöcke zu whitelisten?

Magesetup aktualisieren (auf den develpment branch!) löst das Problem

**Comment by margsenjo** [comment]
Recht hast Du! 
Vielen Dank, hat funktioniert! :)
