### ISSUE TITLE
Magento 1.9.2.2 issue with static blocks

### ISSUE THREAD

**Issue by akkermanronald** [firegento/firegento-magesetup#238]
After migration to 1.9.2.2 we are facing issues with static blocks not displaying on the frontend. 

This has probably to do with the issue described here:

http://www.dudesquare.nl/blog/2015/10/31/static-block-shortcodes-not-working-1-9-2-2/

**Comment by Schrank** [comment]
This is already solved in dev branch: https://github.com/firegento/firegento-magesetup/issues/207

**Comment by akkermanronald** [comment]
Sorry, we should have checked closed issues before opening new issue.

**Comment by Schrank** [comment]
Yes you should :joy: but we should have released it :)

**Comment by akkermanronald** [comment]
We can re-install the dev branch and have to re-run magesetup or is this part of the installer script?

**Comment by Schrank** [comment]
it is an install script, it shoud run automatically after cleaning the cache

**Comment by jcage88** [comment]
I have the same issue too. I use a template from http://www.templatemonster.com for Magento. Can you please help me somehow with it? I don't know what to do :(

**Comment by Schrank** [comment]
I think you need an agency or freelancer who maintains your store. You might want to drop @sprankhub @avstudnitz @therouv or anyone else an email.
