### ISSUE TITLE
Composer Update Fehler in Repo 

### ISSUE THREAD

**Issue by herralda** [firegento/firegento-magesetup#240]
bei Composer Updaten magesetup ergibt sich Fehlermeldung von einem anderen Modul, welche ist bei mir gar nicht installiert:
<tt>
[Composer\Downloader\TransportException]                                                                                          
The "http://packages.firegento.com/AWeberCommunications_EmailMarketing.json" file could not be downloaded (HTTP/1.1 404 Not Found) 
</tt>
Dieser Fehler tritt immer vor, solang die Quelle "http://packages.firegento.com" in composer.json steht.

**Comment by sprankhub** [comment]
This has nothing to do with MageSetup. See https://github.com/magento-hackathon/composer-repository/issues/342
