### ISSUE TITLE
Magento 1.9.2.2 und MageSetup 2.2.3  Nach Update: Impressum wird nicht angezeigt

### ISSUE THREAD

**Issue by adsammcom** [firegento/firegento-magesetup#241]
Die Blöcke "magesetup/imprint_field" & "magesetup/imprint_content" auf der  CMS-Seite Impressum werden nicht angezeigt. Ändert sich auch nicht nach Neuinstallation und löschen des Cache

{{block type="magesetup/imprint_field" value="shop_name"}}

{{block type="magesetup/imprint_content" template="magesetup/imprint/address.phtml"}}

**Comment by Schrank** [comment]
Duplicate #238
