### ISSUE TITLE
Disallowed block magesetup/imprint_field

### ISSUE THREAD

**Issue by KlausStangl** [firegento/firegento-magesetup#243]
Hi!
I've setup a notification every time a block isn't allowed using this solution:
http://www.dudesquare.nl/blog/2015/10/31/static-block-shortcodes-not-working-1-9-2-2/#solution
Now I always get the warning magesetup/imprint_field isn't allowed. I already added a permission in my block white list and also tried to add a variable permission but both don't work.
Any hint would be great!
-Klaus

**Comment by sprankhub** [comment]
Make sure that you added the correct block type (mind any whitespaces etc) and make sure that you cleared the cache. Should be okay then.
