### ISSUE TITLE
Fester Versandkosten Steuer Satz

### ISSUE THREAD

**Issue by RPromo** [firegento/firegento-magesetup#245]
Hallo,

ich habe mal eine Frage. Ist es möglich für die Versandkosten einen festen Steursatz für ein Land zu hinterlegen?

Fragt mich bitte nicht warum aber ich möchte folgendes abbilden.

Shop ist in der Schweiz und versendet nach Deutschland. Produkte sollen mit 0% Steuern angezeigt werden, die Versandkosten aber mit 19%.
Das die Produkte ohne Steurn angezeigt werden ist ja kein Problem, aber wenn ich das richtig sehe nimmt Magento dann auch 0% für die Versandkosten.
Kann ich nicht für die Steuerklasse "Vollbesteuerter Versand" einen Steuersatz hinterlegen? Vieleicht habe ich das ja einfach nur übersehen.

MfG

Christian

**Comment by Schrank** [comment]
Standardmäßig kannst du in Magento einfach einen Steuersatz für die Versandkosten hinterlegen, solange du die Einstellung unten nicht änderst:
![bildschirmfoto 2015-12-17 um 15 52 15](https://cloud.githubusercontent.com/assets/379680/11872568/35a3e264-a4d6-11e5-9070-242a63e67cfa.png)

**Comment by RPromo** [comment]
Ja Danke,

aber wo hinterlege ich das "Vollbesteuerter Versand" zb. 19% sind?

**Comment by Schrank** [comment]
Bei den Steuersätzen. Sales > Tax

**Comment by RPromo** [comment]
Sorry, aber ich finde das einfach nicht.

Ich verstehe die Zuordnung einfach nicht.
Bei Regeln kann ich sagen: Kunden kaufen vollbesteuerte Artikel und die entsprechenden Artikelsteuerklassen und Steuersätze hinzufügen. Bei Artikelsteuerklassen kann ich auch "Vollbesteuerter Versand" auswählen und "Vollbesteuerter Artikel". Bei Steuersatz wähle ich den entsprechenden Steuersatz für den Artikel zum jeweiligen Land aus. Aber wo wähle ich den Steuersatz für die Versandkosten?

**Comment by Schrank** [comment]
System > Configuration > Sales > Tax > Tax Classes

Und so gerne wir die helfen, bitte habe Verständnis dafür, das wir keinen Support leisten können. Wenn du Hilfe brauchst (und das ist nicht mal Teil von MageSetup), suche dir bitte einen der Committer, schreibe sie persönlich an und frage nach einem Angebot.

**Comment by RPromo** [comment]
Sorry, ich dachte ihr hättet das mit MageSetup erweitert.

Soweit ich weis kann Magento keine unterschiedlichen Steuerklassen für Artikel und Versand handhaben. Ich habe da eure Funktion mit der Versandsteuerklasse wohl falsch verstanden.

**Comment by Schrank** [comment]
Kann Magento, hat Magento. Was man leider nicht haben kann out of the box sind unterschiedliche Steuerklassen für den Versand: https://github.com/firegento/firegento-magesetup/issues/205
