### ISSUE TITLE
How to change or add the attribute visible in the cart?

### ISSUE THREAD

**Issue by Anis108** [firegento/firegento-magesetup#246]
Please could somebody tell how to add or at least change the attribute visible in the cart?
Right now its short discription. 

I wish to add two other attribut like weight and brand logo.
An answer or an costumization offer would be nice.

Kind regards
Anis108

**Comment by Schrank** [comment]
You can just edit the attribute under catalog > attributes > attribute

**Comment by Anis108** [comment]
Thanks for the prompt reply it lead to the solution.
After re-indexing it worked!

**Comment by Anis108** [comment]
Can somebody explain the following behavior:

After seting up a few the attributes "show in cart" 
A few are visible immedatily after saving "visible in cart" others dont appear.

While re-indexing is working throu the different indexes.
All attribute becomes visible for a few minutes and disappears with out obvious reason.
Everything is still configured to show in cart. and some attributes are still visible in the cart but others just disappear.
