### ISSUE TITLE
check and optimize for php 7.0 usage

### ISSUE THREAD

**Issue by hpvd** [firegento/firegento-magesetup#248]
check and optimize for php 7.0 usage
Since PHP 7.0 is released and seems to achieve very good speed enhancements
see http://talks.php.net/froscon15#/magentobench
( use links at bottom for details )

and with this Magento 1.9.2.2 can be made easily compatible by using this extension
https://github.com/Inchoo/Inchoo_PHP7 [^]
which includes fixes for all known incompatibilities
see https://magento.stackexchange.com/questions/74008/is-magento-ready-for-php-7/

=> it would be great to check and ensure php 7 compatibility of this extension too.
To spread a word about the status of compatibility in documentation would make it perfect :-)

**Comment by Schrank** [comment]
You may do us a favor and test this :)

**Comment by sprankhub** [comment]
Having a look at the [Travis build](https://travis-ci.org/firegento/firegento-magesetup) indicates that newer versions of Magento (+ MageSetup) work with PHP 7. Mind that the tests are not "complete" though.

**Comment by riconeitzel** [comment]
I'm not a developer and don't know travis. But there's a lot of PHP 7 stuff and it's all green.
