### ISSUE TITLE
extend the imprint content

### ISSUE THREAD

**Issue by packm** [firegento/firegento-magesetup#250]
I need to add a secondary company locacion to the imprint (1. office and 2. base). How can I extend magesetup with a local module to do so?

**Comment by Schrank** [comment]
Have a look into the system.xml and just add a field, then you need to rewrite the imprint block and change it there too I guess.

**Comment by packm** [comment]
> Have a look into the system.xml and just add a field

That was my first idea to change the magesetup system.xml, but this works only till the next update, therefore, I thought to make a local extension extending the community one to prevent any error, until the community extension do not allow to customize/modify the imprint fields.

**Comment by sprankhub** [comment]
Extending the `system.xml` does not mean you have to edit the extension file. You can simply have your own extension with a `system.xml`, which contains the same paths as MageSetup's one. Magento will merge them anyway.
