### ISSUE TITLE
Issues with Best4Mage Configurable Products Simple Prices

### ISSUE THREAD

**Issue by XSized** [firegento/firegento-magesetup#251]
We had OrganicInternet SCP in our shop, got it working with some help from here in firegento. But SCP massivly slows down our shop (TTFB is up to 2 seconds longer with SCP) so I'm testing Best4Mage Configurable Products Simple Prices in our development system. Everything is fine except catalog and search. Firegento completely changes the output for the prices so the extension is unable to show the "Price from:" and the lowest possible price like it should.

Does someone got this working with firegento? Tried different modifications but nothing works. Don't want to go back to SCP...

**Comment by Schrank** [comment]
No clue about the problem, but you can try https://bitbucket.org/modulprogrammierer/dmp_betterconfigurableproducts

**Comment by XSized** [comment]
Tried BCP but it completely destroys the layout on product page if I select "use lowest price as standard" and the lowest price is not visible in category view. We're using porto-theme.
