### ISSUE TITLE
magesetup für Magento 2.0.2

### ISSUE THREAD

**Issue by Ron16** [firegento/firegento-magesetup#252]
Hallo firegento-team,
kurze Frage, kann ich die vorliegende Version von "firegento-magesetup" auch für Magento 2.0.2 verwenden? Wenn ich die Daten entpacke, finde ich die Dateistruktur von Magento 1.xx vor (skin-Ordner usw.)
Freue mich über einen kurzen Tipp.
Vielen Dank schon mal dafür
Ron16

**Comment by riconeitzel** [comment]
Hallo!

nein, dieses Modul hier ist nur Magento 1 kompatibel. Es gibt aber unter https://github.com/firegento/firegento-magesetup2 eine für Magento 2 angepasst Version.

Viele Grüße
 Rico

**Comment by Ron16** [comment]
Hallo, 
vielen Dank :-) da hätt ich ja auch selbst drauf kommen können, sorry nochmal.
Gr. Ron16

**Comment by Ron16** [comment]
Hallo Rico, 
kannst du mir noch eventuell in ein, zwei Stichworten sagen, wie ich die erweiterung nun installieren muss und nicht dabei kaputt mache? Ich bin neu im Umgang mit der Magento Entwickllungsumgebung (ist deshalb vielleicht eine naive Frage) und möchte nichts falsch machen.
Vielen Dank
Gr. Ron16
