### ISSUE TITLE
Nach dem Update werden die Statische Blöcke nicht mehr geladen

### ISSUE THREAD

**Issue by balters** [firegento/firegento-magesetup#253]
Hallo,

ich habe meinen shop von Magento Version 1.9.1.1 auf Magento Version 1.9.2.4 erneuert und muss leider feststellen das  Statische Blöcke nicht mehr geladen werden.

Da es auch die z.b. AGB betrifft unter shop/index.php/magesetup/frontend/agreements/id/1/ dachte poste ich es mal hier.

Auch den Blöcken (magesetup/mrg_business_terms) die entsprechenden Rechte unter "System -> Berechtigungen -> Blocks" zu geben brachte nicht die Lösung.

**Comment by sprankhub** [comment]
Du bist dir ganz sicher, dass du die Blöcke `cms/block`, `magesetup/imprint_field` sowie `magesetup/imprint_content` erlaubt hast? Vermutlich nicht...

**Comment by balters** [comment]
Danke für deine schnelle Antwort. Dann schau mal bitte: 
![bildschirmfoto 2016-03-11 um 09 45 02](https://cloud.githubusercontent.com/assets/14022135/13697705/8b7b340e-e76f-11e5-9a13-99bed6a92bdf.png)

**Comment by sprankhub** [comment]
Strange. Cache hast du sicherlich geleert/aktualisiert ;-)

Aber dann kann man aus der Ferne leider nicht mehr sagen... Am besten, du schreibst einen der [Contributor](https://github.com/firegento/firegento-magesetup/graphs/contributors) an für bezahlte Hilfe... Generell funktioniert das nämlich schon...
