### ISSUE TITLE
Add a custom attribute field only on order pdf for each product line.

### ISSUE THREAD

**Issue by BigBlack** [firegento/firegento-magesetup#254]
Hi guys, I'm starting to use firegento, but I need to add a particular attribute field, only to the order document, in particular it is the original product code, so I can send my order document directly to the supplier that can read directly this one to understand which product I need. How can I do that?

**Comment by sprankhub** [comment]
Please do not get me wrong, but this has nothing to do with MageSetup. I guess [Magento StackExchange](https://magento.stackexchange.com/) would be a better place for such a question.

Anyway a quick idea: When you edit an attribute, you can say that it should be visible in checkout:
![image](https://cloud.githubusercontent.com/assets/930199/13771167/4790ee58-ea8c-11e5-8cdd-80840078dc9b.png)

I am currently not sure if this also means that it is visible on the PDF, but it is worth a try.

**Comment by BigBlack** [comment]
Ok but I need only to be visible in the order pdf.. However I try and post on stackexchange. Thank you! Bye

**Comment by Schrank** [comment]
To make it clear: Visible on checkout means visible on cart and on review (not on PDF).

**Comment by BigBlack** [comment]
Yeah, your are right, I was no clear. In particular I need to show this attribute only to my supplier. I was thinking that magendo create an order pdf to send with mail, but i think, there isn't this native option. So first I need to find a way to generate this pdf, then I think to have found the way to insert this attribute to pdf. 

I've added in Default.php under core/Firegento/PDF/Models/Items those lines.
`$prod = Mage::getModel('catalog/product')->load($item->getProductId());
		$codice_fornitore = $prod->getAttributeText(codice_fornitore);
                $lines[][] = array(
                'text' => Mage::helper('core/string')->str_split('Codice Fornitore : ' . $codice_fornitore, 60, true, true),
                'font' => 'italic',
                'feed' => 120
            );`
They seems to work in the invoice even if I don't undestand yet, how to ovveride this file. 
However I need to put this code to generate an order pdf to send to my supplier, If automated, after the payment is registered, even better.

**Comment by Schrank** [comment]
FireGento_Pdf is over here: https://github.com/firegento/firegento-pdf if you need more help, please change the repo :)

**Comment by epiblue** [comment]
@BigBlack 

hello, can you explain the code you've posted? Please... I'm trying to add a Condition Comment to my invoices and can't get it to work... 

Here's my attribute, could you please help me with this? Sorry, newbie on the subject...

Here's the atribute details, attribute id 134: (
http://imgur.com/a/Og1dP

I've changed the code to (for testing):
`$prod = Mage::getModel('catalog/product')->load($item->getProductId());`
`$codice_fornitore = $prod->getAttributeText(condition_desc);`

`// Get condition note`
`		$lines[][] = array( `
`			'text' => Mage::helper('core/string')->str_split('Condition comment2 : ' . $codice_fornitore, 134, true, true), `
			`'font' => 'italic', `
`			'feed' => 134`
`		);`

But it doesn't work,
Thanks a lot,
