### ISSUE TITLE
agreement popup is empty

### ISSUE THREAD

**Issue by cluster007** [firegento/firegento-magesetup#260]
Hello,
i´m using magento Version 1.9.2.4 with magesetup Version 2.2.2. i put something in my shopping-cart and if i want to checkout and want to Show the agb, linked /frontend/agreements/id/1/ there is no further Content shown. i have reinstalled magesetup and can´t find where to Change or solve the Problem. has someone an idea?
thanks for your help!

**Comment by sprankhub** [comment]
Please check if the following blocks are whitelisted under System > Permissions > Blocks:

- `cms/block`
- `magesetup/imprint_field`
- `magesetup/imprint_content`

**Comment by cluster007** [comment]
Thanks! Works Fine!
