### ISSUE TITLE
Question: Which files does firegento-magesetup touch ?

### ISSUE THREAD

**Issue by philicious** [firegento/firegento-magesetup#262]
Hi, 
I'm about to run Magento in a docker container. For immutability, I need to know which files are created/changed by firegento-magesetup so I can integrate them into the magento image. 
That way the container can be "thrown away" / recreated without the need to do additional setup/config steps by hand via Magento Admin UI. (Its also important if you want to scale the containers horizontally)
Changes to the DB are not relevant as the same DB is reused but the file system is volatile (media is preserverd ofc)

I could diff the container prior/after magesetup is run but I thought I'd ask first.

Thx for your help and the great project!

**Comment by Schrank** [comment]
Not an expert about this but I guess nothing is created. Everything is written to the database.

**Comment by philicious** [comment]
@Schrank that sounds promising, thx! 
(I'll leave the issue open for a few more days and answers/opinions)

**Comment by sprankhub** [comment]
I am also pretty much sure that no files are created by MageSetup. It is all done in the DB.

**Comment by philicious** [comment]
I'm also quite confident by now that it doesnt touch any files which would need to be persisted
