### ISSUE TITLE
We have a problem in /paypal/express/review/

### ISSUE THREAD

**Issue by l-carb-shop** [firegento/firegento-magesetup#263]
Page /paypal/express/review/ is not dispayed in the right way. It is breaking up at the point, where to present agreements. Even footer of page is not shown.

in Apache logs we find:
PHP Fatal error:  Class 'Mage_Germansetup_Helper_Data' not found in /home/l-carb-shop/public_html/app/Mage.php on line 547

We had a system magento 1.7 with germansertup. We updated it to MAgento 1.9 and magesetup. Since this this problem accures

**Comment by Schrank** [comment]
Cache?

**Comment by Schrank** [comment]
Do you have a complete stacktrace?

**Comment by sprankhub** [comment]
Grep for `germansetup` in your code base and in your database and replace any occurrences with `magesetup`. Additionally, check Sales > Terms and conditions.
