### ISSUE TITLE
Traslation in shopping cart

### ISSUE THREAD

**Issue by nernst84** [firegento/firegento-magesetup#270]
Hi,
i've done a website in Italian and when i put somethings into my shopping cart the translation doesn't work! I can see "Short Description" and "Lieferzeit". In app/locale/it_IT i have the csv FireGento_MageSetup.csv correctly traslated in Italian and "Lieferzeit" is traslated in "Tempo di Spedizione" like "Short Description" to "Descrizione Breve" but the translation works only when you are in product page and not when you have a product into your shopping cart. Also if you enable the tranlsation inline for admin you are not able to change these 2 fields.
![firegento](https://cloud.githubusercontent.com/assets/22443978/18828910/4ca6166a-83da-11e6-8873-e0532f34354e.jpg)

Any suggestion?

**Comment by avstudnitz** [comment]
There are product attributes with the codes "short_description" and "delivery_time". You can add store specific labels in Catalog -> Attributes -> Manage Attributes.
![2016-09-26 11_17_13-short_description _ manage attributes _ attributes _ catalog _ magento admin](https://cloud.githubusercontent.com/assets/662059/18829032/cb7b863c-83da-11e6-816d-305244d56e4d.png)

**Comment by nernst84** [comment]
Thanks a lot. It was very helpfull! Now it's perfect!
