### ISSUE TITLE
Problem mit Mehrwertsteuer

### ISSUE THREAD

**Issue by timonalbers** [firegento/firegento-magesetup#271]
Hallo,

wir nutzen euer Modul sehr erfolgreich in unserem Shop. Vielen Dank. Wir haben ebenfalls alle Steuereinstellung von eurem Modul korrekt durchführen lassen.
Beim Erstellen einer Gutschrift wird allerdings die sog. Berichtigungserstattung, bei uns heißt sie nach Übersetzung "Anpassungsrückerstattung" immer in Brutto ohne Steuerabzug angezeigt. Alle anderen Beträge sind aber voll versteuert und richtig. Wie kann ich bspw. einstellen, dass die Steuer bei der Berichtigungserstattung auch gezogen oder ausgewiesen wird oder kann man bspw. einstellen, dass der eingegebene Wert von Anfang an Netto ist? Wir nutzen dies um Preisnachlässe für defekt angelieferte Ware an die Kunden zu geben.

Danke für eure Hilfe.

**Comment by Schrank** [comment]
Hi @timonalbers,

I hope you undestand english. We have a lot of people from other countries, so I switch languages.

What you describe is a magento core problem. Magento calculates the taxes based on the tax amount or tax percent (I can't remember), but nonetheless, there is no easy way to determine which tax class/percentage to use.

I implemented for a customer. We use the highest tax percentage found in the order:
https://gist.github.com/Schrank/896561c841f564efb003c87441e90a4e

I hope this helps
Fabian
