### ISSUE TITLE
Update von germansetup zu magesetup

### ISSUE THREAD

**Issue by Marx15** [firegento/firegento-magesetup#273]
Hallo Support-Team

habe bis jetzt germansetup benutzt. Nach eine Frage zu diese Extension und einen Fehler zur Funktion "Newsletter-An- und -Abmeldungen Historie" (diese hatte noch vor kurze funktioniert. Jetzt lande ich plötzlich auf eine 404 Seite), wurde mir empfohlen einen Update auf magesetup zu machen.
Benutze seit immer Magento Version 1.9.0.1.

Meine Frage ist jetzt ob ich einfach die neue Extension über Connect installieren kann, ohne dass alle meine aktuellen Einstellungen verloren gehen? Muss ich etwas neu einstellen? Kann ich nach der Installation, die germansetup auch im Connect einfach löschen?

Danke schonmal

**Comment by sprankhub** [comment]
http://www.webguys.de/magento-1/tuerchen-18-von-germansetup-zu-magesetup:

> ## Wie funktioniert ein Update von GermanSetup auf MageSetup?
Ganz einfach: MageSetup installieren. GermanSetup wird automatisch deaktiviert und alle Einstellungen werden automatisch übernommen. Die GermanSetup-Dateien können, müssen aber nicht, anschließend entfernt werden. Sollten Anpassungen an den von GermanSetup genutzten Templates gemacht worden sein, müssen die Pfade der angepassten Dateien bearbeitet werden. Aus src/app/design/frontend/base/default/template/germansetup/ wird src/app/design/frontend/base/default/template/magesetup/, aus src/skin/frontend/base/default/css/germansetup/ wird src/skin/frontend/base/default/css/magesetup/. Sollten Rewrites von GermanSetup-Klassen gemacht worden sein, müssen diese natürlich ebenfalls angepasst werden.
