### ISSUE TITLE
Why didn't you rewrite checkout/agreements block?

### ISSUE THREAD

**Issue by vovayatsyuk** [firegento/firegento-magesetup#274]
You are creating your own block with the [same name](https://github.com/firegento/firegento-magesetup/blob/master/src/app/design/frontend/base/default/layout/magesetup.xml#L516) instead.

So, is there any reason for that? I think it would be better to rewrite standard block for third-party checkout modules compatibility.

p.s. Multishipping is using [default block](https://github.com/firegento/firegento-magesetup/blob/master/src/app/design/frontend/base/default/layout/magesetup.xml#L558). Looks like a bug?

**Comment by Schrank** [comment]
> You are creating your own block with the same name instead.

Rewrites are evil and we should try to avoid them at all costs.
I don't think magento has a block with the name `magesetup.checkout.agreements`.

>  Multishipping is using default block. Looks like a bug?

I don't think this is a bug, no one is using multishipping, so no one implements it. Even the payment provider don't implement and test multi shipping most of the time.

But I assume if someone (you? :-)) implements it, we'll merge it :)

**Comment by Schrank** [comment]
> You are creating your own block with the same name instead.

Rewrites are evil and we should try to avoid them at all costs.
I don't think magento has a block with the name `magesetup.checkout.agreements`.

>  Multishipping is using default block. Looks like a bug?

I don't think this is a bug, no one is using multishipping, so no one implements it. Even the payment provider don't implement and test multi shipping most of the time.

But I assume if someone (you? :-)) implements it, we'll merge it :)

**Comment by vovayatsyuk** [comment]
Sorry, I meant you are using same "as" attribute to replace original block in layout.

Third-party modules are using `checkout/agreements` block, and will show all agreements instead of filtered out. They are simply doesn't know that they should use some third-party agreements block instead of standard block.

I think that's the case for rewrite usage. Otherwise, all third-party modules should change their logic when using agreements block.

**Comment by Schrank** [comment]
I'm not sure I can follow you. Do you have an example were a rewrite would be better than this?

**Comment by vovayatsyuk** [comment]
I was talking about third-party one step checkout extensions. Usually they use almost the same blocks as standard checkout does. 

Replacing is good, but it will not work with onestepcheckout modules, because they have another page handle and magesetup instructions will not work on them. This results in filtered agreements at standard checkout and not filtered at other checkout pages.

However, I'm not sure if your agreements template will work out of the box with these modules, so maybe your approach is good to prevent broken onestepcheckout modules.

**Comment by vovayatsyuk** [comment]
Okay, I've fixed my issue by adding a dynamically loaded xml layout update file in case of enabled `Firegento_Magesetup` module with following content:

```xml
<firecheckout_index_index>
    <reference name="checkout.onepage.review">
        <block type="magesetup/checkout_agreements" name="checkout.onepage.agreements" as="agreements" template="magesetup/checkout/onepage/agreements.phtml"/>
    </reference>
</firecheckout_index_index>
```

I think we can close this ticket, if you are not willing to override magento block.

**Comment by riconeitzel** [comment]
@vovayatsyuk I totally understand your point but MageSetup can not be an all-in-one-for-all-3rd-party-extension solution. So if you use custom Checkouts or any other type of 3rd Party it is - I'm very sorry - your responsibility alone to make it work properly.

That's because there are so many different extensions out there that it's technically impossible to provide a compatibility solution for all of them.

AND: If your checkout follows the magento™ way it would have loaded the block by it's alias and thus would work just fine. but it didn't.
