### ISSUE TITLE
Catalog_Product_Price Block returns bool while should return a tax display type id

### ISSUE THREAD

**Issue by PapaDragonov** [firegento/firegento-magesetup#275]
I believe there is a bug in https://github.com/firegento/firegento-magesetup/blob/development/src/app/code/community/FireGento/MageSetup/Block/Catalog/Product/Price.php#L174)

```php
/**
     * Returns whether or not the price contains taxes
     *
     * @return bool Flag if prices are shown with including tax
     */
    public function isIncludingTax()
    {
        if (!$this->getData('is_including_tax')) {
            $includesTax = Mage::helper('tax')->priceIncludesTax(); <--- 
            $this->setData('is_including_tax', $includesTax);
        }
        return $this->getData('is_including_tax');
    }
```

This method is called by the [Price_Info.phtml](https://github.com/firegento/firegento-magesetup/blob/2.1.1/src/app/design/frontend/base/default/template/magesetup/price_info.phtml) template to determine the **tax display type.**  Due to this purpose, up to Version 2.1.1 the above-mentioned method called 

```php
$this->setData('is_including_tax', Mage::getStoreConfig('tax/display/type'));
``` 

what returns an integer between 1 and 3. (The tax display type: excl. / incl. / both.)
Since Version 2.2.1 the method calls 

```php 
$includesTax = Mage::helper('tax')->priceIncludesTax();
``` 

what returns a bool (respectively 1 or 0). Since this value is then in the [Price_Info.phtml](https://github.com/firegento/firegento-magesetup/blob/2.1.1/src/app/design/frontend/base/default/template/magesetup/price_info.phtml) template compared to the `Mage_Tax_Model_Config_DISPLAY_TYPE`-constants that consist of the integers 1 to 3, the tax display type is not determined correctly, is it?
If my general outline is correct, for sure one can alternatively consider this as bug in the mentioned Template File.

**Comment by sprankhub** [comment]
Looks like a bug for me, too.

The method has been changed with https://github.com/firegento/firegento-magesetup/commit/6a203a2fbe20ed94f32f04ef736f8fe236ee1f1b#diff-faec04652749c90389ec4f80889fdcea. Could you have a look at this again @mpaepper? Thanks!

**Comment by riconeitzel** [comment]
@mpaepper Marc?

**Comment by roman204** [comment]
still a bug.... should i revert it to old way of checking tax? cause this is definitly wrong

**Comment by sprankhub** [comment]
@mpaepper could you jump in here?

**Comment by mpaepper** [comment]
Sorry for the late reaction, I only noticed this issue now.

I fixed it in a pull request: https://github.com/firegento/firegento-magesetup/pull/322
