### ISSUE TITLE
Can't use another Tax Rate

### ISSUE THREAD

**Issue by vgaven** [firegento/firegento-magesetup#276]
Steps to reproduce:
Using any browser or operating system.
Using Magento 1.9.3.1 and 1.9.2.4
Using firegento-magesetup.
Settigs- Tax- Default Tax Destination Calculation- Default Country ABC 
Adding a new tax rate like following steps

Create a new tax rate and add it to tax rules to be available 
For example:
Full Tax Rate for Product 18.0000
Discount Tax Rate for Product 8.0000
No Tax Rate for Product 0.0000

create a new Product with price 50.00 and select Discount Rate

Expected Result:
Backend Product Price: 50.00
Backend Product incl. Tax 3.70

Frontend Product Price: 50.00
Frontend Product incl. Tax: 3,70 (which I shoud see if I add it to the cart)

Actual Result:
Backend Product Price: 50.00
Backend Product incl. Tax 3.27

Frontend Product Price: 50.47
Frontend Product incl. Tax: 3,74 (which I see if I add it to the cart)

UPDATE

I noticed that if I change the discount rate from 8 to 7 the tax is calculating correctly, but if changing back  the same problem the calculation works only for discount rate 7 all other integers works bad

**Comment by therouv** [comment]
Hi @vgaven could you please open the issue in the https://github.com/firegento/firegento-magesetup2/ repository because it is related to the M2 version of this module? Thanks!

**Comment by vgaven** [comment]
Hi @therouv I get the problem on Magento 1.9.3.1 and also 1.9.2.4 not M2 but I will try it out on M2 too whether the problem also existing.

**Comment by therouv** [comment]
Hi @vgaven okay, I'll reopen the issue.. I thought it was M2 because you mentioned "firegento-magesetup2" in your issue description above.

**Comment by vgaven** [comment]
@therouv thanks for reopen the issue I am already trying to solve that problem since a few days so I could  post my answer and advice on github, but do not  found any solution to fix so hope you guys have an advice

**Comment by vgaven** [comment]
@therouv its look like that nobody are interested ? A mistake to add that kind of problem here at gihub

**Comment by Schrank** [comment]
Hey @vgaven unfortuantely it is not about interest, but about time and priority. Everyone has a lot of things to do, so working on free projects has not a high priority. If you need things fast er than "it's done when it's done", please feel free to check the [contributors page](https://github.com/firegento/firegento-magesetup/graphs/contributors) and find someone for paid service.

**Comment by vgaven** [comment]
@Schrank I know it would go in this direction but now I will not select any person at the contributors page, reason: There was no person who get back and wrote just a line to explain what kind of problem is present. I would pay more than enough but I think its to late.

**Comment by Schrank** [comment]
I think this is unfair. Because checking for an error alone might take hours. But let's stop this discussion here. Good luck in fixing the bug. We would love to get a PR either from you or any developer who fixes this. Wish you the best!

**Comment by vgaven** [comment]
@Schrank your guys are doing bad PR with giving no answer.  I already talked to a guy in ukrainie he will fixe it. Please close that issue.

**Comment by Schrank** [comment]
Due to the fact that this is a bug, I'll leave it open.

**Comment by riconeitzel** [comment]
@vgaven I'm sure @Schrank meant to get a PullRequest (PR) not PublicRelations … As MageSetup is free to use open source software created voluntary by community members within their spare time I'm fine with your criticism that we're bad with replying. You are right but that's the way voluntary work works.

We don't FORCE people to pay for bugfixes. It's very kind you raised the problem so we can take care on one of our next hackathons. We would be very happy if you decide to contribute your efforts back to this project by submitting the patch that fixes this issue. So can solidarize with all the developers and their work you currently take advantage of.

I hope to hear back from you soon and perhaps including a fix to this annoying bug!

Best,
 Rico

**Comment by sprankhub** [comment]
I just tried to reproduce the issue, but did not succeed. Mind that for a product of 50 EUR, 7% tax are 3,27 EUR and 8% tax are 3,70 EUR. Hence, it seems that you tax rate is not 8%, but 7%.

7% tax:

![image](https://user-images.githubusercontent.com/930199/31583493-849f2be6-b19d-11e7-93c0-fd67ba4e45cd.png)

![image](https://user-images.githubusercontent.com/930199/31583498-8fd5fabc-b19d-11e7-8d3e-4aad7843df2a.png)

8% tax:

![image](https://user-images.githubusercontent.com/930199/31583511-9d44d448-b19d-11e7-982d-40b5b3d8bfae.png)

![image](https://user-images.githubusercontent.com/930199/31583514-a524d35c-b19d-11e7-98d5-e4c48cc9adbf.png)

Seems to be totally fine. And I do not think that this is a MageSetup issue. Please disable MageSetup and do your test again. The problem will probably be the same.
