### ISSUE TITLE
Enhancement > One step checkout - Only one checkbox for all German Law agreements 

### ISSUE THREAD

**Issue by Arn2014** [firegento/firegento-magesetup#279]
Hi,

Im using a one step checkout module and I am trying to improve the checkout proces by replacing the magesetup AGB and Widerrufsbelehrung checkboxes and textfields, by only one single agreements line with 3 html links in it, one to the AGB page , one to the Widerrufsbelehrung and one to the Datenschutz page.

Example:

(checkbox) Mit Absenden der Bestellung erkläre ich mich den **Datenschutzbestimmungen**, der **Widerrufsbelehrung** und **AGB** einverstanden.

This way the checkout is much cleaner in terms of visible layout en therefore more customer friendly 
in terms of usability..

How can his be done?

mit freundlichen grüßen 

A

**Comment by riconeitzel** [comment]
Hi, that behaviour is especially forbidden by german law. That's why it is explicitly done as it's done in MageSetup.

You can create a custom agreement with all three blocks.

If you need support you can ask for paid services.

Best,
Rico

**Comment by Arn2014** [comment]
Okay thanks for your info ! 

Mfg
A
