### ISSUE TITLE
Magento 1.9.3 und Firegento-Magesetup

### ISSUE THREAD

**Issue by giorgiojob** [firegento/firegento-magesetup#280]
Da es für Magento 1.9.3 keine deutsche Lokalisierung gibt habe ich über Mittwald zusammen über den Installationsservice Magnet 1.9.3 zusammen mit firegento-magestupals deutsche Lokalisierung installiert. 
Soweit alles gut nur bekommen ich in den angelegten Seite z.B. Impressum und in den angelegten Mailvorlagen einfach die Inhalte der dort hinterlegen Block Aufrufe nicht angezeigt. Nach Recherche im Netz stellte ich fest, daß diese firegento-magesetup Version (letzte verfügbare und 2 Jahre alt) gar nicht mit Magento 1.9.3 kompatibel ist. Wird aber bei Mittwald leider damit zusammen installiert.
Meine Frage ist nun wie kann ich es hinbekommen, daß die Blöcke aufgerufen werden bzw. was sollte ich bei dem Aufruf der Blöcke ändern daß da ein Inhalt angezeigt wird also wie muss der dort hinterlegt Link aussehen, das da funktionieren kann. Eventuell einfach das eintragen, was bei magento standardmässig verwendet wird und wenn ja was steht denn da dann für ein Link z.B. für den hier, der jetzt eingebaut ist beim Impressum: 

{{block type="magesetup/imprint_field" value="shop_name"}}

Sollte vermutlich statt "magesetup" was anderes drin stehen. 
Schnelle Hilfe wäre echt nett verbieg mir hier schon seit 4 Tagen die Finger und komme einfach nicht weiter.

**Comment by riconeitzel** [comment]
Hi,

wir verwenden MageSetup auch mit 1.9.3.1

Schau mal unter System > Berechtigungen > Blocks

Dort müssen alle Blockbezeichner (bswp magesetup/imprint_field) aufgeführt werden, die in Eingabefeldern im Backend irgendwo verwendet werden.

Viele Grüße
 Rico

**Comment by riconeitzel** [comment]
So sieht das bspw. bei einem unserer Kunden aus:

```
1	core/template	Allowed
2	catalog/product_new	Allowed
3	magesetup/imprint_field	Allowed
4	magesetup/imprint_content	Allowed
5	cms/block	Allowed
7	imprint/field	Allowed
8	imprint/content	Allowed
9	text/css	Allowed
10	easybanner/banner	Allowed
11	catalog/product_list	Allowed
12	reports/product_viewed	Allowed
13	reports/product_compared	Allowed
```

**Comment by giorgiojob** [comment]
Hi,

nah das ist ja der Hammer! Kaum zu Ende geschrieben, schon eine Antwort und die auch noch mitten ins schwarze.
Vielen Dank! Soweit ich mich entsinnen kann wurde das bei der 1.9.1 noch automatisch angelegt.
Da wäre ich auch nach einem weiteren Tag nicht drauf gekommen.
Du rettest Weihnachten!

Danke

Gruß

Giorgio

**Comment by riconeitzel** [comment]
Das sollte es auch so. Ich schätze, dass da mal wieder die Mittwald-Spezialitäten dazwischen funken.

Viele Grüße
 Rico

**Comment by Schrank** [comment]
Mittwald nimmt bestimmt die connect version. Nimm hier mal den develop bramch, der ist besser und auch stable!

**Comment by giorgiojob** [comment]
Ich werde denen das mal mitteilen und dann können die den Fehler suchen.
Vielen Dank nochmal und spannende Weihnachten und einen guten Rutsch

Gruß

Giorgio

**Comment by giorgiojob** [comment]
develop bramch

Wie komme ich da ran?
Und dann einfach per FTP über die bestehende Installation schieben?

Gruß

Giorgio

**Comment by giorgiojob** [comment]
Noch eine Frage.

In der jetzt installierten firegento magesetup Version war leider kein spanisch mit drin.
Woher bekomme ich den eine spanische Sprachversion für die Magento 1.9.3 Version.
Bei Connect konnte ich nichts finden war als Extension mit 1.9.3 kompatibel ist.

Gruß

Giorgio

**Comment by Schrank** [comment]
Dev branch: oben rechts download zip, dann am besten ordentlich deployen... git wäre gut. Ftp bringt viele probleme, klappt aber zur not.

Spanisch: keine ahnung, spanier fragen, nicht unsere baustelle

**Comment by giorgiojob** [comment]
Vielen Dank nochmal!
