### ISSUE TITLE
MageSetup, keine automatische Erzeugung von Meta Tags

### ISSUE THREAD

**Issue by kasimir24** [firegento/firegento-magesetup#281]
Magento 1.9.3.1
Installation von MageSetup ohne Beanstandungen. Erst bei Datentransfer vom Magento-Shop zum Google Merchant Center wurden Fehler für zu lange Description-Einträge angezeigt. Da Google zuerst nach Meta Tags sucht und nur wenn keine gefunden werden auf die "description" zugreift, habe ich Veranlassung gesehen mir die "Meta Informationen" der Artikel-Information anzusehen. Es sind keinerlei Meta Tags generiert worden, obwohl die Verwendung des "meta_autogenerate" Attributes auf ja gestellt ist. Im Anhang das belegende Bild. Was läuft schief?
![meta information](https://cloud.githubusercontent.com/assets/25057448/21851088/e33f1644-d80d-11e6-85a8-4abfe2aad519.jpg)

**Comment by sprankhub** [comment]
1. Welche MageSetup Version? Die letzte getaggte 2.2.3, development branch, master branch?
2. MageSetup generiert diese Informationen dann, wenn der Artikel gespeichert wird. Wenn der Artikel schon existierte, du dann MageSetup installiert hast und den Artikel danach nicht mehr gespeichert hast, kann noch nichts generiert worden sein. Insofern: Wird etwas generiert, wenn du bei dem Artikel manuell auf "Speichern" drückst?

**Comment by kasimir24** [comment]
Danke für den Hinweis.
Zu 1. 2.2.3 Master
Zu 2. Ich habe die Artikel mittels Magmi importiert und aktualisiere sie mittels eines Cronjobs. Nun sind in erster Instanz ca. 5500 Artikel erfasst. Manuelles Speichern ist da keine wirklich gute Option. Ein weiterer Punkt als Schwierigkeit - die Frage nach dem Gewicht, denn es handelt sich um virtuelle Artikel. Obwohl virtuelle Produkte als Grundeinstellung festgelegt wurden, wird nach dem Gewicht gefragt.
Frage, wie kann ich den Speichervorgang komfortabler lösen um zu den Meta Tags zu gelangen.

**Comment by therouv** [comment]
@kasimir24 Es muss das Event `catalog_product_save_before` getriggert werden, damit sie automatisch generiert werden. Habe leider mit magmi keine Erfahrung, weshalb ich nicht weiß, ob die das tun. Alternativ Script schreiben, der das erledigt.

**Comment by Schrank** [comment]
@therouv magmi kippt direkt in die DB. Die werfen keine events.

Einmalig script schreiben, loop über alle produkte, einfach überall das event triggern und gut.

Lass es auf der cli laufen, dann hast du kein Problem mit max_execution_time @kasimir24
