### ISSUE TITLE
Drop PHP 5.3/4/5 Support

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-magesetup#283]
I would love to drop PHP 5 support at all, but there are a lot of people out there which still use PHP5.

What about dropping PHP 5.5 support?

**Comment by sprankhub** [comment]
I think we should support all versions with security support according to https://secure.php.net/supported-versions.php. Hence, PHP 5.6 upwards would be fine for me. We simply have to state that clearly in the README.

**Comment by tniebergall** [comment]
Magento 1 and some third party module do not (officially) support PHP7, so we should at least support php5.6.

**Comment by avstudnitz** [comment]
I wouldn't put in PHP 5.6+ only compatible code on purpose. I wouldn't test the module on 5.5- any more, we can change the min version in the readme to 5.6, but we shouldn't make it incompatible on purpose.

**Comment by Schrank** [comment]
Lets become constructive - please add to your comment:

"I want MageSetup to Support PHP <version>", like:

I want MageSetup to Support PHP 5.5+

**Comment by schmengler** [comment]
I want MageSetup to support PHP 5.6+

**Comment by EliasKotlyar** [comment]
I am wondering which kind of features would drop the support? "Return type declarations"? Am i missing some really cool stuff on php7?

**Comment by Schrank** [comment]
The root of the question is [] (PHP 5.4+) for me. But the next step is: What do people need? If no one is running PHP 5.6 anymore (which is surely not the case), there is no need to take care of PHP 5 anymore :-) And every dropped version is a problem less and a feature more.

**Comment by tobi-pb** [comment]
5.6+

**Comment by ingohill** [comment]
I want MageSetup to support PHP 5.6+

**Comment by Morgy93** [comment]
I want MageSetup to Support PHP 5.6+

**Comment by razbakov** [comment]
I want MageSetup to support PHP 5.6+

**Comment by avstudnitz** [comment]
I want MageSetup to support PHP 5.5+. Don't break backwards compatibility on purpose please.

**Comment by davidverholen** [comment]
I want MageSetup to support PHP 5.6+    as < 5.6 has reached end of life and won't even get security updates anymore (http://php.net/supported-versions.php). As Andreas said, you may not want to break 5.5 compatibility on purpose just to use some new fancy language constructs ;)

**Comment by therouv** [comment]
I want MageSetup to support PHP 5.6+. 
Don't break BC on purpose please.

**Comment by riconeitzel** [comment]
@Schrank what is the conclusion from your point of view?! :D least common option? 5.5+?

**Comment by Schrank** [comment]
It seems no one wants to go with supported PHP versions 😂  So, I guess we stay with 5.5

**Comment by riconeitzel** [comment]
@Schrank can we close this ticket as the code base already is 5.5+?
