### ISSUE TITLE
Baseprice/Grundpreis

### ISSUE THREAD

**Issue by anjenehm** [firegento/firegento-magesetup#284]
Hey Mates,

i miss the Baseprice/Grundpreis Module.

Since pangv law in germany, we are looking for a
working solution for that. 

Can you provide me a link for that module/script?

But at all many thanks to your guys for the firegento-magesetup!

Best regards

**Comment by Schrank** [comment]
There are the two modules from "the modulprogrammierer"

- https://bitbucket.org/netresearch/dmp_baseprice
- https://bitbucket.org/netresearch/dmp_basepricepro

but unfortunately there is no license, therefore you have to talk to https://www.netresearch.de/ or  http://de.nr-apps.com/ to find a license agreement.

**Comment by anjenehm** [comment]
I found this solution for me too, but it provide the issue that bundle products pirce the "price as configured" is without tax. And other products have price update issues.

Thanks for you help!
