### ISSUE TITLE
MageSetup configuration not showing up

### ISSUE THREAD

**Issue by zlep** [firegento/firegento-magesetup#285]
Hi, I installed MageSetup by extracting all files in Magento root but after Logout/Login the configuration is not showing up. I tried it a few times now with fresh Magento installations (1.9.3.2) but it's not working.
I installed the German Local package first. I also tried enabling Symlinks. It's not showing up.

It's not my first Magento installation. I already installed MageSetup in the past and never had problems.

Any ideas what I can do?
Thanks

**Comment by Schrank** [comment]
Either you didn't flush the cache or maybe the files were dropped in the wrong location?

**Comment by riconeitzel** [comment]
Sounds like 'CACHE' or wrong directories … can you see MageSetup in your magento "app/etc/modules/" directory?

**Comment by Schrank** [comment]
If you have any problems, tell us. For the moment I'll close this.

**Comment by zlep** [comment]
Hi, thanks.
Flushed all caches, removed all files from var/cache. Still the same problem. 

It's strange, MageSetup is not in app/etc/modules/

What's wrong?

**Comment by Schrank** [comment]
You didn't install it properly :)

**Comment by sprankhub** [comment]
If you do not have the file `FireGento_Magesetup.xml` under `app/etc/modules/`, you did not copy the files to the correct location. Mind that you have to copy the contents from the `src` folder into your Magento root.

**Comment by zlep** [comment]
You're absolutely right guys. It seems I'm too stupid today. It's not the first time I'm installing MageSetup and still I have to figure out why it does not extract the FireGento_Magesetup.xml

Thank you. I guess I will get it working now :)
