### ISSUE TITLE
'Agreements not confirmed' on /customer/account/create/

### ISSUE THREAD

**Issue by zlep** [firegento/firegento-magesetup#286]
Hi, I'm getting 'Agreements not confirmed' (Bedingungen wurden nicht bestätigt.) on /customer/account/create/ on a fresh Magento 1.9.3.2 installation with German Local and Magesetup.

Would be really nice if anybody could tell me where this error comes from because there is no checkbox or anything for agreement.

Thank you very much in advance.

Could this have to do with frontend/base/default/template/magesetup/customer/form/tc-confirmation.phtml
This block is empty on the frontend. (No checkbox or anything, just nothing where the user could agree). Could I just turn off that the user has to agree if he registers?

**Comment by sprankhub** [comment]
Could you provide a screenshot from Sales > Terms and conditions? For each agreement, please check the "Display on" attribute. Is there any agreement, which is set to "on customer registration"?

**Comment by zlep** [comment]
Hi, thx, please find the screenshot attached.
They are all set to display "in checkout".
![untitled-5](https://cloud.githubusercontent.com/assets/10477541/23410464/a44fe48a-fdcf-11e6-9164-ce1060baccba.jpg)


Is the agreement for "Kundenregistrierung" missing?

**Comment by sprankhub** [comment]
Okay, this may be a bug. I will check that. If you do not need it, there should not be any agreement for customer registration.

Do you sell digital goods or services? If not, try to disable these agreements.

**Comment by zlep** [comment]
Thank you very much. I'm really looking forward to your fix. Just to let you know: I installed the latest release (_array). Might have to do with it? I guess I shouldn't have installed this release. Anyway, I hope you can fix it. Thanks in advance.

**Comment by Schrank** [comment]
You should try with develop branch from github :)

**Comment by zlep** [comment]
Yeah, but can I go "back" to the develop branch? If I go back I have to delete all magesetup files, right? This could "destroy" my configuration, doesn't it? Maybe it's better to wait for a fix? :)

**Comment by Schrank** [comment]
Configuration is in database, so less of a risk - I assume you don't do that on product, right? RIGHT!? :)

**Comment by zlep** [comment]
No :) I did't even add products, though. So, manually deleting all magesetup files and installing development branch would be the way to go? Thanks

**Comment by zlep** [comment]
Just for info: I installed the development branch which works fine.

**Comment by sprankhub** [comment]
Awesome!
