### ISSUE TITLE
Not valid template file:adminhtml/base/default/template/magesetup/imprint/email_footer.phtml class: FireGento_MageSetup_Block_Imprint_Content

### ISSUE THREAD

**Issue by Elfen-Service** [firegento/firegento-magesetup#292]
Happens when creating / editing customer from backend ...

**Comment by riconeitzel** [comment]
@Elfen-Service which MageSetup version do you currently use? Which Magento Version do you currently use?

**Comment by Elfen-Service** [comment]
Latest MageSetup from the master branch and Magento CE 1.9.3.2 ...

**Comment by sprankhub** [comment]
I just tested this in various ways and cannot reproduce it, sorry :/
