### ISSUE TITLE
Tax calculation shown up some wired data, but the summary is right

### ISSUE THREAD

**Issue by Grueff** [firegento/firegento-magesetup#295]
![screeen](https://cloud.githubusercontent.com/assets/28363995/25678844/6f39d838-304b-11e7-804c-3b235818044f.PNG)
As you see on the screenshot, the tax calculation is doin some wired stuff.
All products from this order are 7% and the shipping is also 7%.
The same wired stuff shows up on a pdf invoice.
I dont know what causes this bug, maybe does anybody had the same problem or maybe a location where i could search for it?
Thank you

**Comment by riconeitzel** [comment]
Can you screenshot your tax configurations? (product tax classes, customer tax classes, tax rules, tax rates) I suspect a duplication and a wrong assignment on the product level.

Rico

**Comment by Grueff** [comment]
WOW What a fast response! Thank you!
![screen2](https://cloud.githubusercontent.com/assets/28363995/25679061/46d9875c-304c-11e7-8f4d-8a59f55fd81c.PNG)
![screen3](https://cloud.githubusercontent.com/assets/28363995/25679062/47d4e804-304c-11e7-93c3-892b4b82424a.PNG)

**Comment by riconeitzel** [comment]
nah - I'm talking about Verkäufe > Steuern :-)

**Comment by Grueff** [comment]
Uhm... Sorry =)
![screen4](https://cloud.githubusercontent.com/assets/28363995/25679327/3e7a53ce-304d-11e7-8ab4-6a7e26578721.PNG)
![screen7](https://cloud.githubusercontent.com/assets/28363995/25679328/3e7c23ca-304d-11e7-8d5b-778a85e97c56.PNG)
![screen6](https://cloud.githubusercontent.com/assets/28363995/25679329/3e7ddbca-304d-11e7-91d8-228e369d1a29.PNG)
![screen5](https://cloud.githubusercontent.com/assets/28363995/25679330/3e7e974a-304d-11e7-8996-7f3b632d0f20.PNG)

**Comment by riconeitzel** [comment]
Okay - so the only valid tax line is 1,19 € which is correct and is based on the real calculation. Did you compare the sales_flat_* tables with your backend rendering? so: is there a reason why it could lead to 3 different tax classes showing up?

**Comment by Grueff** [comment]
I checked out the sales_flat_order and sales_flat_invoice but i cant find one of the wrong taxes shown up in the backend. :-(

**Comment by riconeitzel** [comment]
are there any other 3rd party extension installed?

**Comment by Grueff** [comment]
Yes,
IWD One Page Checkout, DHL Intraship (deactivated), DHL Online Retoure (deactivated), Aoe_Scheduler, Valdecode_CookieLaw, Sashas_Confimages, AuIt_SearchAssistant  and some Magik extensions from the template.
I thought about the products, most of the ordered products are configurable products.
Only 2nd the product (priced 6,99 €) was not configurable.
The 1st product (5,99 €) got another size with a price of 8,99 €, the 3rd product (5,19 €) got  another size with a price of 13,20 €.
But none is 19%, i also found out that the 19% are in other orders the same amount, allways!
We use the Sashas Confimages extension for the right presentation of the configurable products, but i dont think that this would interrupt the price calculation?

**Comment by riconeitzel** [comment]
Okay … well with all the information till now: I have no idea where these entries are coming from.

You can do yourself a favor by troubleshooting the following:
1.) turn off all 3rd party modules (incl. magesetup) and review this order again
2.) turn off all 3rd party modules (excl. magesetup) and review this order again.

if the error persists with 1.) keep all extension turned off and re-order! Check if the wrong taxes are stored in the new order
if the error persists with 2.) keep all extensions turned off but magesetup and re-order! Check if the wrong taxes are stored in the new order

if the error does not appear with 1 and/or 2 turn on one module at a time and retest the scenario till you find the problem.

Note: This issue might also be raised by bogus templates. you can try to turn off your custom themes and run it with a default magento core theme. 
Note 2: This issue might also be raised by core-hacked core files. If you don't have a history (git) you have to check/compare the core files as well.

Rico

**Comment by Grueff** [comment]
Sorry for my late response, got a busy day.
I'll try today your suggestions and then i will report. Maybe i could help another user also.
Thank you for your great help!

**Comment by Grueff** [comment]
After 2 days of searching, uninstalling and so on.
I found the bug deep in my DB.
We had some test orders and used a SQL Script to remove em.
But this script didnt removed the entrys in sales_order_tax, so our shop used that again.
After removing the old entrys everything was fine.

**Comment by Schrank** [comment]
Good to hear that - kind of :-) Great you found the problem!
