### ISSUE TITLE
Duplicate DE tax rates

### ISSUE THREAD

**Issue by sreichel** [firegento/firegento-magesetup#299]
Only for germany taxes rates where added two times.

![tax_rates_de](https://cloud.githubusercontent.com/assets/5022236/25953314/3c9471a4-3663-11e7-9cd0-6346065e05b7.PNG)

**Comment by Schrank** [comment]
Can you please add informations to reproduce that? I never encountered that.

**Comment by sreichel** [comment]
What information do you need?

- Magento 1.9
- multistore setup with 3 websites / 4 stores / 16 views

**Comment by riconeitzel** [comment]
you can - theoretically - rerun the tax setup which will delete all tax entries and recreate them …

**Comment by avstudnitz** [comment]
Careful with that - create a backup before, and don't do it on the live server if you haven't tested it somewhere else!

**Comment by sreichel** [comment]
Fortunately i had a testsystem w/o MageSetup installed .... same behavior here.

Again 1.9.3.1 and only a handful extensions that do not effect countries/tax/...

**Comment by riconeitzel** [comment]
when you ran the setup: did you MAP the tax classes?

**Comment by sreichel** [comment]
I've used default settings, just hitted "install".

**Comment by riconeitzel** [comment]
you have to read through the options to know what you install! 😂

do it again and look for tax settings -> map your tax classes!

**Comment by sreichel** [comment]
Real lads don't read manuals ... LOL

I'm not sure wath you mean with "map your tax classes"

![tax_rates_de_2](https://cloud.githubusercontent.com/assets/5022236/25956550/4f02f758-366c-11e7-9035-e62a6000f363.PNG)

**Comment by sreichel** [comment]
You you please try it yourself?

I assume the checkbox has to be set to configure tax settings properly ... but this results in duplicated DE entries.

**Comment by Schrank** [comment]
I can't reproduce your problem. If I click on `Run MageSetup` all tax_calculation_rates are deleted and rewritten.

The only idea I have to produce this result is to click two times fast enough on the button. And I can' t reproduce this either.
