### ISSUE TITLE
newsletter_subscriber_save_after

### ISSUE THREAD

**Issue by jg-development** [firegento/firegento-magesetup#303]
Hi,
ich habe ein Problem mit MageSetup (2.4.1) und mc-magento (1.1.7).
Im generellen gibt es ja den Hook, so dass nach jedem save eines subscribers dieser aufgerufen wird.
Mit der Mailchimp API hat es nun das Problem, dass dieser Hook immer aufgerufen wird und somit die Newsletter Subscriber Historie permanent ansteigen lässt.

Die Tabelle newsletter_subscriber hat durch mailchimp unter anderem "mailchimp_sync_delta" bekommen. Das heisst eigentlich bei jedem mailchimp api cron werden die Newslettersubscriber angepasst.
Ich hab so inzwischen je nach Shop 20 Mio Einträge in der Datenbank zu Subscriber-Historie.
Es wäre gut, wenn man die Historie deaktivieren könnte, oder verhindert, dass diese Einträge permanent erzeugt werden.
Jan

```
733 	foo@test.de 	Abonniert 	09.06.2017 23:37:06
733 	foo@test.de 	Abonniert 	09.06.2017 23:45:10
733 	foo@test.de 	Abonniert 	09.06.2017 23:45:10
733 	foo@test.de 	Abonniert 	09.06.2017 23:40:10
733 	foo@test.de 	Abonniert 	09.06.2017 23:40:10
733 	foo@test.de 	Abonniert 	09.06.2017 23:50:02
733 	foo@test.de 	Abonniert 	09.06.2017 23:37:09
733 	foo@test.de 	Abonniert 	09.06.2017 23:37:09
733 	foo@test.de 	Abonniert 	09.06.2017 23:45:03
733 	foo@test.de 	Abonniert 	09.06.2017 23:37:11 
```

**Comment by Schrank** [comment]
Was hält dich davon ab, den Observer von MageSetup zu deaktivieren?

**Comment by jg-development** [comment]
Im Prinzip nix, ich kann den observer natürlich in der xml deaktivieren, aber wäre es nicht besser wenn der observer nachcheckt ob der eintrag schon vorhanden ist, indem nur die magento spalten verwendet werden?

**Comment by jg-development** [comment]
@Schrank : Vlt. kann man ja auch eine Einstellung im Backend hinzufügen, mit welcher man den Observer deaktivieren kann?

**Comment by Schrank** [comment]
Meiner Meinung nach - und ich lasse mich hier gerne von anderen Maintainern korrigieren - macht es keinen Sinn ein Modul an andere Module anzupassen. Dann fangen wir bei Mailchimp an und hören nie wieder auf. Wenn das Modul Probleme mit anderen Modulen macht, sehe ich es als Aufgabe der Shopbetreiber an, das Problem zu lösen. Die Priorität ändert sich, aus wirtschaftlichen Gründen, wenn es ein Bezahlmodul ist. Aber da das hier Open Source ist, macht es meiner Meinung nach schlicht zuviel Arbeit.

Das war der Philosophische Teil, jetzt ein ganz praktisches Problem: Wir müssen dokumentieren, wer sich wann an- und abmeldet. Das heißt ein Besucher/Kunde kann sich mehrmals an- und abmelden. Wir haben meiner Meinung nach schlechte Chancen zu verstehen, ob ein Eintrag gerade gemacht wurde, weil Mailchimp irgendwas speichert oder weil der Benutzer seinen Status geändert hat - aber es ist spät, hoffentlich habe ich hier einen Denkfehler.

Deaktivier den Observer in der Konfig, egal wie das hier ausgeht, erfahrungsgemäß dauert es, bis das im Modul landet - wenn es schnell gehen soll, freuen wir uns über einen Pull Request :-)

**Comment by Schrank** [comment]
> @Schrank : Vlt. kann man ja auch eine Einstellung im Backend hinzufügen, mit welcher man den Observer deaktivieren kann?

Der Observer ist nötig, nach deutscher Rechtssprechung, d.h. so eine Option bietet mehr Potential für Unheil. Dann lieber pfiffige Entwickler wie dir die Änderung in der XML überlassen :-)

Ich würde übrigens eine eigene XML nehmen und nicht die vom Modul, falls das nicht klar sein sollte

**Comment by jg-development** [comment]
Ok, die Rechtssprechung hatte ich dabei nicht im Blick. Das aus Updategründen usw. ein eigener genommen wird, dass sehe ich sowieso genauso.

**Comment by Schrank** [comment]
Ja, wie sovieles in dem Modul ist das nicht unsere Idee :-(

**Comment by DocOlson** [comment]
Ein einfacher Check im Observer kann einen weiteren Eintrag in der Tabelle sparen. Das halte ich auch unabhängig von externen Modulen für sinnvoll. Siehe https://github.com/firegento/firegento-magesetup/issues/310

**Comment by Schrank** [comment]
@jg-development Ich fürchte ich habe das Problem nicht verstanden :( Dank @DocOlson ist das jetzt (endlich) bei mir angekommen und ja, das gehört geändert.
