### ISSUE TITLE
Invalid Attribute Type when activating Terms and Conditions

### ISSUE THREAD

**Issue by anjenehm** [firegento/firegento-magesetup#304]
When i activate at the backend System -> Configruration -> Sales -> Checkout Terms and Conditions at the last step it shows me invalid attribute type.

Logfile: 2017-06-28T07:17:02+00:00 DEBUG (7): Attribute: revocation_product_type

I have readed that firegento uses these attribute.

How can we solve this issue?

**Comment by sprankhub** [comment]
As you can see [here](https://github.com/firegento/firegento-magesetup/blob/802d5ffbdfb375993287e03d268a1d3af5cd36e8/src/app/code/community/FireGento/MageSetup/sql/magesetup_setup/mysql4-upgrade-2.1.1-2.2.0.php#L35), this attribute is added in the upgrade from `2.1.1` to `2.2.0`. Did you clear the cache? If not, do it.
Check the resource version in `core_resource`. If you do not have the attribute in `eav_attribute` and the magesetup version in `core_resource` is >= `2.2.0`, you may consider setting it to e.g. `2.1.1` again, so that the setup script is executed again.

**Comment by anjenehm** [comment]
I have allready the version 2.2.2 in my backend FireGento_MageSetup 2.2.2 (stable) 
under /app/code/community/FireGento/MageSetup/sql/magesetup_setup latest mysql4-upgrade-2.2.0-2.2.1.php 

How can i execute it again?

Maybe you can explain it in german?

**Comment by sprankhub** [comment]
Do you find the attribute `revocation_product_type` in the `eav_attribute` table?

**Comment by anjenehm** [comment]
No only in core config data

![image](https://user-images.githubusercontent.com/7089704/27636359-7d7f1002-5c0b-11e7-86a8-d915d7d5987a.png)

**Comment by sprankhub** [comment]
This means that the setup script has not been executed correctly. You can set the magesetup version in `core_resource` back to e.g. `2.2.1` and clear the cache. The setup script should be executed then.
Anyway, you should check which setup scripts have not been executed. Maybe you have to lower the version number even more.

**Comment by anjenehm** [comment]
**You can set the magesetup version in core_resource back to e.g. 2.2.1 and clear the cache.**


How that?

**Comment by Schrank** [comment]
Go into the table core_resource and set data_version and version to 2.2.1

But as @sprankhub already said: If you are not totally sure what you are doing, you might miss more settings.

**Comment by anjenehm** [comment]
Okay it dont solve this issue. So i never can activate terms & conditions? :o 
or is there a workaround to solve this?

**Comment by Schrank** [comment]
Fixing these kind of problems is far beyond our non-profit free support (which doesn't exist). Find a magento developer who fixes this for you.

Most of us are open for paid support, so just drop Simon, Andreas, nhp, me or anyone else an email.

**Comment by anjenehm** [comment]
Okay i understand thanks for help!

But just the last question. Isnt there an option to make a sql command for that? :(

**Comment by sprankhub** [comment]
No. These scripts are usually executed and DB updates should definitely be done via these scripts. Not via direct SQL commands.

**Comment by Schrank** [comment]
There is an SQL command for that in the data and sql scripts, but something is broken with your installation.

**Comment by anjenehm** [comment]
Okay Shop should go online today... this is the last part i stucked... But many thanks for explain me my issue :(
