### ISSUE TITLE
Taxrules don´t Fit

### ISSUE THREAD

**Issue by baenschplus** [firegento/firegento-magesetup#306]
We moved a Shop from Magento 1.7.X with German Setup to a new installation with 1.9.3.4 and MageSetup. Now now the total netto and total brutto are ever including 19%, it doesn´t matter from which country i place the order. also the tax free Customer Class doesn´t fit. it shows all prices in netto but the netto total and brutto total are ever on Brutto like calculated with 19% from Germany. 

In the Tax row it show 0,00 €. Settings are just like before. And in the old shop everything is still working fine. so we already configured the Taxrules new/again with magesetup but didn´t work.
is this a conflict between fragments of german setup and magesetup, somewhere in the database? i think it couldn't be, but could be one reason.

![settings](https://user-images.githubusercontent.com/12641045/28812242-192881b2-7694-11e7-9c29-40387747011c.jpeg)

![taxes](https://user-images.githubusercontent.com/12641045/28812212-f3d5fe6c-7693-11e7-94e3-254e3988a69a.jpg)
 
thanks so far. Greetings eike

**Comment by Schrank** [comment]
hi @baenschplus and thanks for the report.

> is this a conflict between fragments of german setup and magesetup, somewhere in the database?

MageSetup deactivates GermanSetup, so this is not the reason.

But to be honest, I don't understand the problem.

Can you please tell us:

- What did you try?
- What did you expect?
- What happened instead?

**Comment by sprankhub** [comment]
Closing this because of missing feedback.
