### ISSUE TITLE
Error in File mysql4-install-0.5.0.php 

### ISSUE THREAD

**Issue by wesselsangeln** [firegento/firegento-magesetup#307]
Hello,

I'm getting an error while installing firegento through downloader. 
![firegento_error](https://user-images.githubusercontent.com/31467879/29859476-851fce7c-8d62-11e7-8cd1-b662a95fbcb9.png)
![firegento_error2](https://user-images.githubusercontent.com/31467879/29859484-8a49a2e2-8d62-11e7-82c0-2bc92e217904.png)
![firegento_error3](https://user-images.githubusercontent.com/31467879/29859488-8e4440b4-8d62-11e7-80e1-33bce47c7303.png)

Can anybody assist with that?

**Comment by Schrank** [comment]
Is this a fresh magento?
Which version?

> The error says: You already has an attribute group with the name General and the ID 9. 

We don't create this attribute group. And it should already exist imho. Maybe it is the wrong name, because you installed Magento with another language then english, then the group name might be something else. But even then, the group should just be created and everything is fine.

**Comment by wesselsangeln** [comment]
Hi, 

it is a fresh installed magento with the german magento version. 
It is: Magento Version 1.9.3.4

**Comment by Schrank** [comment]
Btw, thanks for the report and finding the way here. Just woke up, so my "being nice and kind"-module was not loaded yet.

I currently don't have the capacity to dig into it for free, so you can reset and try again this way: https://github.com/firegento/firegento-magesetup#installation

**Comment by wesselsangeln** [comment]
Hi, no problem :) 

I tried it this way you've send me and now I get:

Not Found

The requested URL /index.php/admin was not found on this server.
Apache Server at dr10434.webspaceconfig.de Port 443

**Comment by riconeitzel** [comment]
Did you use the software manager to install magento?

**Comment by Schrank** [comment]
This sounds like the .htaccess is missing

**Comment by wesselsangeln** [comment]
@riconeitzel First i tried to install it via donwloader yes

@Schrank .htaccess is still available

**Comment by wesselsangeln** [comment]
404 is gone now

But the error still applies:

Error in file: "/var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/app/code/community/FireGento/MageSetup/sql/magesetup_setup/mysql4-install-0.5.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9-General' for key 'UNQ_EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME', query was: INSERT INTO `eav_attribute_group` (`attribute_set_id`, `attribute_group_name`, `default_id`, `sort_order`) VALUES (?, ?, ?, ?)

Trace:
#0 /var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '2.4.1')
#2 /var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('2.4.1')
#3 /var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/app/code/core/Mage/Core/Model/App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 /var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /var/www/vhosts/dr10434.webspaceconfig.de/httpdocs/index.php(83): Mage::run('', 'store')
#8 {main}

**Comment by sprankhub** [comment]
I cannot reproduce this issue at all. Feel free to contact one of the maintainers or your developer for paid support. Sorry that I cannot give you any better answer :(
