### ISSUE TITLE
USt.-frei gem. Kleinuntern.-Reg. §19 UStG

### ISSUE THREAD

**Issue by Evoco1** [firegento/firegento-magesetup#31]
Hallo zusammen wie ihr seht bin ich neu hier,
ich würde mich freuen wenn ihr mir helfen könntet.

Ich habe die Extension “Firgento German Shop Setup” in mein Magento Shop der auf der Community Version 1.8.1 läuft auf wie von euch empfohlen auf firegento-MageSetup upgedated und integriert.

Dadurch das ich aber Kleinunternehmer bin suche ich eine Möglichkeit anstelle der Anzeige „Inkl. 19% MwSt.“ würde ich gerne „USt.-frei gem. Kleinuntern.-Reg. §19 UStG“ einfügen.

Leider kann ich bei Ihrer Extension solch eine Möglichkeit nicht finden hier kann man nur auf „Inkl. 0 % MwSt.“ umstellen was rechtlich problematisch ist.

Können ihr mir eventuell ein Workaround oder eine Idee nennen wir ich dies in die Extension einspielen kann.

Über eine Idee und Rückmeldung würde ich mich sehr freuen.

Vielen Dank.

**Comment by therouv** [comment]
Anpassung sollte im Shop selbst vorgenommen werden und nicht im MageSetup Modul.
