### ISSUE TITLE
New entry in newsletter_subscriber_status on each save

### ISSUE THREAD

**Issue by DocOlson** [firegento/firegento-magesetup#310]
Whenever a newsletter subscriber gets saved into the database a new entry in the newsletter_subscriber_status will be created even if the subscriber data has not changed.

This came to my attention when I installed the mailchimp module. Mailchimp has the habbit of updating ALL subscribers when pushing it's data to the store. So the newsletter_subscriber_status table kept filling up rapidly.

So, doesn't it make sense to add a check in the observer whether the subscriber's data has actually changed?

Suggestion:

```
public function saveSubscriberStatusHistory(Varien_Event_Observer $observer)
{
	try {
		/* @var $subscriber Mage_Newsletter_Model_Subscriber */
		$subscriber = $observer->getEvent()->getSubscriber();

		if ($subscriber->hasDataChanges()) {
			/* @var $status FireGento_MageSetup_Model_Newsletter_Subscriber_Status */
			$status = Mage::getModel('magesetup/newsletter_subscriber_status');
			$status->setData('subscriber', $subscriber->getId());
			$status->setData('status', $subscriber->getData('subscriber_status'));
			$status->setData('email', $subscriber->getData('subscriber_email'));
			$status->setData('created_at', now());
			$status->save();
		}
	} catch (Exception $e) {
		Mage::logException($e);
	}
}

```

**Comment by Schrank** [comment]
We would love to see a PR!

And one suggestion from my side: I prefer early exits, like this:

```
public function saveSubscriberStatusHistory(Varien_Event_Observer $observer)
{
	try {
		/* @var $subscriber Mage_Newsletter_Model_Subscriber */
		$subscriber = $observer->getEvent()->getSubscriber();

		if (!$subscriber->hasDataChanges()) {
			return;
		}
		/* @var $status FireGento_MageSetup_Model_Newsletter_Subscriber_Status */
		$status = Mage::getModel('magesetup/newsletter_subscriber_status');
		$status->setData('subscriber', $subscriber->getId());
		$status->setData('status', $subscriber->getData('subscriber_status'));
		$status->setData('email', $subscriber->getData('subscriber_email'));
		$status->setData('created_at', now());
		$status->save();
	} catch (Exception $e) {
		Mage::logException($e);
	}
}

**Comment by DocOlson** [comment]
Just checked... makes even more sense to to check for the status field alone (($subscriber->dataHasChangedFor('subscriber_status')) since that is what this table is all about. If anything else changes it would not matter, does it?

Ok... pull request. I have no effing clue how to...

**Comment by Schrank** [comment]
Oh, damn. I'm short on time currently. You should join one of our hackathons! There are no more this year, but next (not published yet) if you want to learn how to PR (and make Magento friends :-)) https://shop.firegento.com/

How to PR: https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

I'll try to do it next week.

**Comment by Schrank** [comment]
And no, we have at least to check status and email. It is all about to tell a lawyer and judge, why someone got an email. If we only log the status (but not the email change) this might be a problem.

**Comment by DocOlson** [comment]
Thank you. Also low on time here :(

Final proposal:

```
public function saveSubscriberStatusHistory(Varien_Event_Observer $observer)
{
	try {
		/* @var $subscriber Mage_Newsletter_Model_Subscriber */
		$subscriber = $observer->getEvent()->getSubscriber();

		if (
			$subscriber->dataHasChangedFor('subscriber_status') ||
			$subscriber->dataHasChangedFor('subscriber_email')
		) {
			/* @var $status FireGento_MageSetup_Model_Newsletter_Subscriber_Status */
			$status = Mage::getModel('magesetup/newsletter_subscriber_status');
			$status->setData('subscriber', $subscriber->getId());
			$status->setData('status', $subscriber->getData('subscriber_status'));
			$status->setData('email', $subscriber->getData('subscriber_email'));
			$status->setData('created_at', now());
			$status->save();
		}
	} catch (Exception $e) {
		Mage::logException($e);
	}
}
```

It checks for changes in email OR status. This should cover it.

**Comment by jg-development** [comment]
Hi @DocOlson ,
I added the pull request with your proposal in the issue #303 .
