### ISSUE TITLE
Where to put files in, if having a custom theme...

### ISSUE THREAD

**Issue by Supermario72** [firegento/firegento-magesetup#312]
Hi everyone.

As "newbie" I please need to know, how to copy the files to my installation 1-9.3.6
I have a custom theme...
Do I have to put files in "base" or "rwd", or in my custom theme.

Thanks in advance!

**Comment by Schrank** [comment]
you copy it exactly the way it is, magento will pick up the files with a fallback from (package/theme|translation|skin|...)

custom/custom
custom/default
base/default

I'm, sure I forgot something here, but it doesn't matter. Copy the files as they are :-)

**Comment by Supermario72** [comment]
Thanks a lot ;-)

**Comment by Supermario72** [comment]
One question.
I understand... all Files from scr to the root, but what about the "docs" folder???
Do I have to copy it in the root, or its content?
What about the single files ".gitignore, .travis.yml, composer etc etc..." 
Do I need them?
Do I have to copy them in the root?

Sorry for this "easy" questions ;-)

**Comment by Supermario72** [comment]
The FOLDER "scr" into / or the content of "scr" into / ???
