### ISSUE TITLE
E-Mail Footer wird nicht angezeigt

### ISSUE THREAD

**Issue by kai1083** [firegento/firegento-magesetup#315]
In allen Mails wird der Footer nicht angezeigt.

Ich würde ganz gerne den Start {{template config_path="design/email/footer"}} in den Mails haben.
Und dort die rechtlichen Angaben hinterlegen.

Magento Version:  1.9.3.4

**Comment by Schrank** [comment]
Das sollte gehen.

Hast du in der Config was hinterlegt? Bist du sicher, dass es nicht durch den Store View überschrieben wird?

**Comment by sprankhub** [comment]
Closing due to lack of feedback.
