### ISSUE TITLE
Search autocomplete stopped working

### ISSUE THREAD

**Issue by Moppelfett** [firegento/firegento-magesetup#316]
After installing German Setup the Magento search auto complete stopped working.
Any experiences here to so,be the problem?
Magento Version is 1.9.3.6

**Comment by sprankhub** [comment]
This should not be related to MageSetup at all. I never heard about that.

Did you clear the cache and reindex? Afterwards, check server and Magento logs and check the autocomplete AJAX call via the network tab in the developer tools. Try to disable MageSetup under `app/etc/modules` and see if it really works again afterwards.
