### ISSUE TITLE
Tax value in frontend rounded?

### ISSUE THREAD

**Issue by wi-holzem** [firegento/firegento-magesetup#319]
Hello,

in Switzerland, the VAT has changed from 8% to 7.7%. 
I changed this in Magento but in the Fronted it still displayed 8%.
Does "$this->getFormattedTaxRate()" round up the Tax Rate value?

Thank you for your answer.

**Comment by Schrank** [comment]
I would wonder if that is the case. But I can't check currently. 

https://github.com/firegento/firegento-magesetup/blob/development/src/app/code/community/FireGento/MageSetup/Block/Catalog/Product/Price.php#L149-L162

**Comment by sprankhub** [comment]
I just checked it and changed `19.0000` to `19.5000`. Both, on the category page and on the product page it is displayed correctly as `Incl. 19.5% Tax`.

Please check if you hardcoded the tax rate in your template or if you did not clear your cache.

**Comment by wi-holzem** [comment]
Thank you, 
We have recently taken over the support of the shop.
i checked this and the value 8% was hardcoded in FireGento_GermanSetup.csv 
`"Excl. %s Tax","Zzgl. 8% MwSt."` 
but if i chage this to `"Excl. %s Tax","Zzgl. %s MwSt."` %s will not be replaced with the tax value.
In the Frontend %s is displayed.

**Comment by wi-holzem** [comment]
There is no FireGento_MageSetup.csv
and no price_info.phtml in the theme.
the code of the price_info.phtml is attached
[price_info.phtml.txt](https://github.com/firegento/firegento-magesetup/files/1677035/price_info.phtml.txt)

**Comment by sprankhub** [comment]
You use the very old `GermanSetup` and should update to `MageSetup`.

Anyway, as a quick fix, replace `$this->__( 'Excl. %s Tax' )` with `$this->__( 'Excl. %s Tax', $this->getFormattedTaxRate() )` in your `price_info.phtml`.

**Comment by wi-holzem** [comment]
Thank you very much
