### ISSUE TITLE
Magento 2 Firegento Magestup VAT display 0% tax - MwSt.-Anzeige 0% Steuern

### ISSUE THREAD

**Issue by magepur** [firegento/firegento-magesetup#320]
Hello,

I installed the extension step by step following the instructions, emptied cache and re-indexed everything. I have checked country options, localization and shop information. Everything is registered correctly. But unfortunately everywhere in the products "incl. 0% taxes". Maybe someone knows why that could be?

-----
Hallo,

ich habe die Extension nach der Anleitung Schritt für Schritt installiert, Cache geleert und alles neu indexiert. Länderoptionen, Lokalisierung und Shopinformationen habe ich überprüft. Alles ist richtig eingetragen. Aber leider steht überall in den Produkten "inkl. 0% Steuern". Weiß jemand vielleicht, woran das liegen könnte?

**Comment by Schrank** [comment]
- Check wether taxes are configured
- Check the product has a product tax class (which is configured)
- check the NOT_LOGGED_IN customer group has a tax class (which is configured)
- Check the your default tax country is set
- Make sure your default tax country has to pay taxes

**Comment by magepur** [comment]
@Schrank thanks Schrank, I will check it and then write the solution here.

**Comment by sprankhub** [comment]
You mention Magento 2 in the title. Mind that this is the M1 repository. Please double check your Magento version and the MageSetup version. You find MageSetup for M2 under https://github.com/firegento/firegento-magesetup2.

**Comment by magepur** [comment]
@sprankhub  Thanks for the hint. I have installed the new version for Magento 2, but accidentally posted the problem with Magento 1.
