### ISSUE TITLE
SQL Fehler im Checkout

### ISSUE THREAD

**Issue by twosg** [firegento/firegento-magesetup#326]
Nach Update auf 2.4.2 erhalte ich folgende Meldung im Checkout:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'position' in 'order clause', query was: 

SELECT `main_table`.* FROM `checkout_agreement` AS `main_table`
INNER JOIN `checkout_agreement_store` AS `store_table_2` ON main_table.agreement_id = store_table_2.agreement_id 
WHERE (store_table_2.store_id IN ('2', 0)) AND (`is_active` = '1') 
GROUP BY `main_table`.`agreement_id` ORDER BY position ASC
```

Das passiert aufgrund einer Änderung in der /app/code/community/FireGento/MageSetup/Model/Observer.php, Zeile 81:

`$agreements->setOrder('position', Varien_Data_Collection::SORT_ORDER_ASC);`.

Auskommentieren löst das Problem und ich sehe auch keine Nachteile dadurch.

**Comment by Schrank** [comment]
Das sollte hier angelegt werden:
https://github.com/firegento/firegento-magesetup/blob/development/src/app/code/community/FireGento/MageSetup/sql/magesetup_setup/mysql4-upgrade-2.4.1-2.4.2.php

**Comment by twosg** [comment]
Stimmt - das lief wohl bei mir nicht, sorry :)
