### ISSUE TITLE
How to integerate Magesetup in Accelerated Mobile Pages

### ISSUE THREAD

**Issue by gino2014** [firegento/firegento-magesetup#328]
Dear Community,

we are using magesetup now for years and it works fine. Now we added at a teststore a Accelerated Mobile Pages extension and the following details are not shown
"Inkl. 19% MwSt., zzgl. Versandkosten" 
Does someone know how can wie add this information at AMP pages?
Thanks in advance

**Comment by Schrank** [comment]
The price info is added here:

https://github.com/firegento/firegento-magesetup/blob/development/src/app/design/frontend/base/default/layout/magesetup.xml#L28-L32

So I guess you have to add the layout info to your layout handles.
