### ISSUE TITLE
Minimize collected data (GDPR/DSGOV)

### ISSUE THREAD

**Issue by sreichel** [firegento/firegento-magesetup#329]
For GDPR compliance we were told to reduce collected data ... https://www.it-recht-kanzlei.de/kontaktformular-datenschutzgrundverordnung-dsgvo.html#abschnitt_41

**Contact form:**

- name should not be required
- either phone or mail

**Checkout:**

- phone should be optional

Should this module cover GDRP - as far as possible?

**Comment by riconeitzel** [comment]
Will covered by #338 and #339
