### ISSUE TITLE
Display different taxes, when using special group prices with different tax groups

### ISSUE THREAD

**Issue by sibbl** [firegento/firegento-magesetup#33]
I am trying to have two customer groups A and B, whereas A gets prices shown with 19% taxes and B without taxes, so 0%.

I do have products, where I want the price to be shown with or without taxes, which matches the customers group. So I say that the product has a general price of 10€, and a group price of 7€ for customer group B. However, when viewing the product as customer of group B, I get the product shown for 7€ including 19% taxes.

How can I get the price to be shown with 0% taxes?

Thanks!

**Comment by therouv** [comment]
Fixed in 48c0c84
