### ISSUE TITLE
“Agreements not confirmed.” in customer registration

### ISSUE THREAD

**Issue by cagcoach** [firegento/firegento-magesetup#330]
Hey people,

I try to add an agreement checkbox to the customer registration. For this I added an aggreement in the admin panel at "Sales > Billing Agreements" and selected "On customer registration" at the "Display on" menu.

While checkout, this works fine.

Using the user registration page, no agreements show up and the registration returns "Agreements not confirmed." ("Bedingungen wurden nicht bestätigt.").

From the translation table, I can say that (at least) the error message comes from Firegento. So I suspect that a few lines of code containing the agreements are just missing. But which?

Greedings, Christian

**Comment by Schrank** [comment]
Did you test it with a custom theme? Please try with the default theme. If it works, please diff your customer.xml (or any other layout file which interferes with your customer registration) a block/reference might be missing.

**Comment by cagcoach** [comment]
Even when switching to base/default or default/default theme, the error occours... (magento 1.9.2.4)

**Comment by riconeitzel** [comment]
Do you use a custom checkout module or is it Magento‘s onepagecheckout?

**Comment by cagcoach** [comment]
The problem is not in the checkout... the checkout works perfectly... The problem ist the <ROOT>/index.php/customer/account/create/ page...
BTW yes... default onepagecheckout...

**Comment by cagcoach** [comment]
AccessShop_ThemeOptions
AspenDigital_WysiwygFiles
B71a_FixHiddenCheckoutConfig
BL_CustomGrid
BlueVisionTec_GoogleShoppingApi
Brander_PaymentFee
Cm_RedisSession
Cube_CategoryBestsellers
Cube_CategoryFeatured
DerModPro_BasePrice
Dhl_LocationFinder
ET_RussianLanguagePack
Ecomus_Mediabox
FireGento_GermanSetup
FireGento_MageSetup
Flagbit_ChangeAttributeSet
Fooman_Common
Fooman_GoogleAnalyticsPlus
German_LocalePackDe
Innoexts_ShippingTablerate
ItalianLocale_Info
Iways_PayPalPlus
Ld_Admingrid
Mage_Admin
Mage_AdminNotification
Mage_Api
Mage_Api2
Mage_Authorizenet
Mage_Backup
Mage_Bundle
Mage_Captcha
Mage_Catalog
Mage_CatalogIndex
Mage_CatalogInventory
Mage_CatalogRule
Mage_CatalogSearch
Mage_Centinel
Mage_Checkout
Mage_Cms
Mage_Compiler
Mage_ConfigurableSwatches
Mage_Connect
Mage_Contacts
Mage_Core
Mage_Cron
Mage_CurrencySymbol
Mage_Customer
Mage_Dataflow
Mage_Directory
Mage_Downloadable
Mage_Eav
Mage_GiftMessage
Mage_GoogleAnalytics
Mage_GoogleCheckout
Mage_ImportExport
Mage_Index
Mage_Install
Mage_Log
Mage_Media
Mage_Newsletter
Mage_Oauth
Mage_Page
Mage_PageCache
Mage_Paygate
Mage_Payment
Mage_Paypal
Mage_PaypalUk
Mage_Persistent
Mage_Poll
Mage_ProductAlert
Mage_Rating
Mage_Reports
Mage_Review
Mage_Rss
Mage_Rule
Mage_Sales
Mage_SalesRule
Mage_Sendfriend
Mage_Shipping
Mage_Sitemap
Mage_Tag
Mage_Tax
Mage_Usa
Mage_Weee
Mage_Widget
Mage_Wishlist
Mage_XmlConnect
Magebuzz_Snippet
Philwinkle_Fixerio
Phoenix_Moneybookers
Phpro_Translate
Studioforty9_Recaptcha
Trustedshops_Trustedshops
ZealousWeb_GTranslator

**Comment by riconeitzel** [comment]
Please remove germansetup!

This is an old version of magesetup and interferes with it!

FireGento_GermanSetup
FireGento_MageSetup

**Comment by cagcoach** [comment]
removed FireGento_GermanSetup: no change... still not working...

**Comment by cagcoach** [comment]
I solved the problem. The "Studioforty9_Recaptcha" plugin overrides the form.additional.info block and thus deletes, the agreements. Eventhough Recaptcha was disabled for creating accounts. Thanks to everyone. Closed.

**Comment by Schrank** [comment]
Thanks for the feedback! Good to hear!
