### ISSUE TITLE
Extension data's Migration from Magento 1 to Magento 2

### ISSUE THREAD

**Issue by vtamaan** [firegento/firegento-magesetup#350]
Since we have used same Magento 1 extension in our store and we are upgrading our store Magento 1 to Magento 2 so Does this extension provide any service or script to migrate Magento 1's data to Magento 2?

**Comment by sprankhub** [comment]
MageSetup does not have any "own" data one could migrate. We mainly configure stuff. Hence, these changes are automatically applied if you use the official data migration tool.
