### ISSUE TITLE
Keine Buttons bei Neukundenregistrierung wenn Bestellbedingungen deaktiviert.

### ISSUE THREAD

**Issue by Commercers** [firegento/firegento-magesetup#48]
Ähnlich wie bei Issue 197 bei  firegento-germansetup (https://github.com/firegento/firegento-germansetup/issues/197 ) fehlen mir bei deaktivierten Bestellbedingungen (System > Konfiguration > Zur Kasse > Bestellbedingungen aktivieren ) die Buttons bei /customer/account/create/ (bei Galathemes Templates zusätzlich auch das Layout der Seite). Aktiviere ich die Bestellbedingungen, sind die Buttons (und auch das Layout des Galathemes) wieder da, jedoch gibt es keine Bestellbedingungen auf der create Seite.
Besteht das Problem allgemein?

**Comment by ottonet** [comment]
Ich hab hier das gleiche problem. Auch bei uns (zwei verschiedene templates, beide basiert auf default/base) fehlen die buttons bei /customer/account/create. Deaktiviere Ich Firegento/magesetup dann sind die buttons wieder zurück.

**Comment by therouv** [comment]
@Commercers @ottonet Bugfix wurde mit 3af18f1 vorgenommen und ist schon im Branch `development` enthalten.
