### ISSUE TITLE
Steuerausgabe "inkl. 19 MwSt." im Checkout.

### ISSUE THREAD

**Issue by paul-hph** [firegento/firegento-magesetup#54]
**Folgende Einstellungen:**

![image](https://f.cloud.github.com/assets/3603487/2420536/0b721b72-ab73-11e3-8a43-9a81efb770cf.png)

**führen zu folgender Ausgabe:**

![image](https://f.cloud.github.com/assets/3603487/2420533/000a7ed2-ab73-11e3-8f76-52db8f1adb57.png)
## 

**Problem:**
- es ist nicht ersichtlich was zzgl. und was inkl. ist. 
- die MwSt sollte korrekt ausgewiesen werden. 

**Vorschlag:**

Der Steuersatz-Titel aus **"Verkäufe>Steuer>Steuerzonen und Sätze verwalten"**sollte ausgegeben werden.

> "Steuer" -->  "inkl. 19% MwSt."
## 

```
Magento Version 1.8.1.0
```

**Comment by all4pages** [comment]
Ich schliesse mich paul-siteway an. Sein Vorschlag ist berechtigt und richtig.

**Comment by mklooss** [comment]
der Eingriff hier denke geht zu Tief rein und ist daher nicht ein Bestandteil von MageSetup.
In den meisten Shops ist es zudem simpel per Übersetzung zu setzen.

**Comment by riconeitzel** [comment]
Ich gebe sowohl @paul-siteway als auch @therouv Recht. Vielleicht wäre eine Idee für einen Hackathon: Steuerausgabemodul Firegento_TaxDisplay oder so.

In der Tat ist "das Problem" (@paul-siteway) mit Templates und Übersetzungen "in den Griff" zu bekommen. Die standardmäßig ausgeklappten steuern beispielsweise im Checkout oder die korrekte Darstellung in den Emails.

Viele Grüße
 Rico
