### ISSUE TITLE
Delivery Time - upsell products?

### ISSUE THREAD

**Issue by Netzlichter** [firegento/firegento-magesetup#58]
Hallo,
wie kann ich die delivery time unter den upsell products anzeigen lassen? (How can I show delivery time on upsell products?)
Das ist der code der upsell.phtml:
![delivery-time-upsell](https://cloud.githubusercontent.com/assets/7253495/2670572/790cf690-c0cf-11e3-98bc-0cfd21296ba6.jpg)

Ich bekomme es einfach nicht hin. Es wäre toll wenn ihr mir einen Tipp geben würdet. :)

Vielen Dank!
Grüße!

**Comment by avstudnitz** [comment]
Please confirm that for the attribute "delivery_time" the option "Visible in Checkout Process" ("Sichtbar im Bestellprozess") is activated. With the current "development" version (we fixed a bug about that today) it should work as you described.
