### ISSUE TITLE
Modularisierung der Info Texte

### ISSUE THREAD

**Issue by amenk** [firegento/firegento-magesetup#59]
seht ihr Chancen diese Änderung zu mergen:

https://github.com/amenk/firegento-germansetup/blob/imi/src/app/code/community/FireGento/GermanSetup/Block/Catalog/Product/Price/Info.php

**Comment by therouv** [comment]
Da in der Zwischenzeit einige Änderungen vorgenommen wurden und der Tatsache, dass die Änderungen noch GermanSetup betreffen, schließen wir dieses Issue.

@amenk Sollte dies aber noch gewünscht sein, bitte einen neuen Pull-Request für MageSetup stellen.
