### ISSUE TITLE
Mwst Gets added twice

### ISSUE THREAD

**Issue by berlinwebstudio** [firegento/firegento-magesetup#65]
When checking out or in Shopping cart - when products are set in configuration to be entered in admin - excluding tax as per screenshot

![configuration___system___magento_admin](https://cloud.githubusercontent.com/assets/4682369/2926947/aa6564c0-d763-11e3-874b-34eeaa327107.png)

![apple_ipad_2_-_buy_online](https://cloud.githubusercontent.com/assets/4682369/2926965/fb03686e-d763-11e3-9ef6-3f7ba5404e51.png)

![shopping_cart](https://cloud.githubusercontent.com/assets/4682369/2926977/3497ac02-d764-11e3-92a3-1698b86b5be9.png)

Tax is added twice!

**Comment by avstudnitz** [comment]
MageSetup gives a default tax setup which is working for prices including taxes. It should work if you set it "excluding tax" - if it doesn't, it's a magento bug. We just setting configuration options and creating tax rules, we don't modify the tax calculation in any way.
