### ISSUE TITLE
Shipping modules stop working

### ISSUE THREAD

**Issue by adocom** [firegento/firegento-magesetup#66]
I already asked in magento connect than saw this tracker which seems to be more active, so I just ask the same again :)

With installation of MageSetup, all shipping modules but freeshipping, flatrate und tablerates stop working, even custom shipping modules.
The problem is, they are not displaying in frontend / checkout, in backend everything works fine.

I think the problem lies with "sallowspecific" but even selecting all countries will have no effect. Is there any place to activate different shipping modules?

Tested with fresh installed Magento 1.8.1, Shipping UPS is working. Install MageSetup UPS stops working.

**Comment by avstudnitz** [comment]
MageSetup doesn't modify shipping at all. I think it's some other issue.
