### ISSUE TITLE
How the remove vat information from the category pages

### ISSUE THREAD

**Issue by binaryboys** [firegento/firegento-magesetup#68]
I live in Germany and by law we only need to display the vat information before the client adds the product to his basket. On our site he can only do that from the product details page. But the magesetup is putting the price on the category pages and I would like to disable that. So far I can only make that information invisible but google doesn't like invisible context and I still have per page 60 times the same information what effects not only the keyword density but also the prominence. Please shown e on how disable tax display on the category pages (including homepage)

**Comment by wolf223** [comment]
if you still want to know how to do that, just open your styles.css file and scroll down to the last line and insert following code:

.category-products .tax-details { display: none;}


you don't need to create an observer etc. for this.

**Comment by Schrank** [comment]
We should create an FAQ for the extension, if you ask me right in the readme. For the time being I locked the issue and reopend, so people can see it.

**Comment by riconeitzel** [comment]
https://github.com/firegento/firegento-magesetup/wiki/FAQ
