### ISSUE TITLE
PayPal Integration in Magento nach Installation kaputt

### ISSUE THREAD

**Issue by StefanBr** [firegento/firegento-magesetup#71]
Bei Magento Version 1.9 funktioniert die Einbindung von PayPal nach der Installation von MageSetup nicht mehr. Es steht einem nur mehr PayPal Express zur Verfügung.

**Comment by rasfoel** [comment]
Mit diesem Modul man PayPal Standar Payment einfach reaktivieren.
http://shop.hankeme.de/paypal-standard-payment-revival
