### ISSUE TITLE
"Inkl. Mwst" on Bundled-Products 

### ISSUE THREAD

**Issue by aterjung** [firegento/firegento-magesetup#77]
Hi,

is this issue from germanSetup solved in mageSetup until now? 

https://github.com/firegento/firegento-germansetup/issues/126

I have a problem with bundled products, not showing the right price in case  they are not in stock (MwSt. is not added). Additionally, no tax info is added. I looked into the mageSetup source and the dev-code mentioned in the linked issue is not added. Is there any work in progress on this issue in the moment?

thanks in advance
 
Aike

**Comment by therouv** [comment]
Issue was already solved. Closing.

**Comment by andi1984** [comment]
(y) You saved my day!
