### ISSUE TITLE
Future problem with tax__classes__shipping_tax_class config in tax.xml

### ISSUE THREAD

**Issue by diglin** [firegento/firegento-magesetup#8]
After the merge will be done from the branch 'eu_tax_setup', a possible issue will come with the tax configuration 'tax__classes__shipping_tax_class'. At the moment, it's a fixed ID which is set. With the new logic to generate tax rules, this ID is not anymore directly known. So the value should be taken during the process of tax rules generation or based on the rule defined in tax.xml (tax_calculation_rules)

**Comment by therouv** [comment]
That's just the way it is for now.. Closed.
