### ISSUE TITLE
Apple Mail problem with E-Mail Templates + Attachment

### ISSUE THREAD

**Issue by aterjung** [firegento/firegento-magesetup#99]
Hi,

this is not a problem made by magesetup itself, but it could be fixed in magesetup ip think. If you install a extension to add pdf Attachments to your E-Mail (like Fooman Email Attachments) your customers using Apple Mail can not see the attachment, cause it is hidden behind the big body table used in the mail templates.

The reason for this is the height=100% in the header of the templates:

<body style="background: #F6F6F6; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; margin: 0; padding: 0;">
    <div style="background: #F6F6F6; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; margin: 0; padding: 0;">
        <table cellspacing="0" cellpadding="0" border="0" height="100%" width="100%">

change it to 

<body style="background: #F6F6F6; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; margin: 0; padding: 0;">
    <div style="background: #F6F6F6; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; margin: 0; padding: 0;">
        <table cellspacing="0" cellpadding="0" border="0" width="100%">

and it is ok. 

What do you think?

**Comment by therouv** [comment]
Hi, as you said: it is no MageSetup Problem itself and should be fixed individually.
